### ISSUE TITLE
Error when using InlinePanel

### ISSUE THREAD

**Issue by agelinas** [infoportugal/wagtail-modeltranslation#10]
wagtail-modeltranslation is working rather well for me with the exception of handling InlinePanel in torchbox/wagtail-torchbox setup I have customized. Also, I'm wondering if the new wagtail streamfield can be used with modeltranslation?

Here is some sample code with InlinePanel which triggers an error (I placed an arrow next to one of the lines triggering an error):

BlogPage.content_panels = [
    FieldPanel('title', classname="full title"),
--> InlinePanel(BlogPage, 'related_author', label="Author"),
    FieldPanel('author_left'),
    FieldPanel('date'),
    FieldPanel('intro', classname="full"),
    FieldPanel('body', classname="full"),
#    StreamFieldPanel('streamfield'),
#    InlinePanel(BlogPage, 'related_links', label="Related links"),
#    InlinePanel(BlogPage, 'tags', label="Tags")
]
(I had to comment out StreamFieldPanel and all InlinePanels to get rid of error message)

Here are a few significant lines from the debugging screen:

AttributeError at /admin/pages/new/core/blogpage/3/

type object 'BlogPage' has no attribute 'panels'

(...)

Exception Location: 	/var/www/htac/htacweb/wagtail_modeltranslation/models.py in _patch_inlinepanel, line 216

It's great having modeltranslation working for Wagtail! Thank you|

**Comment by rmartins90** [comment]
Thanks for your feedback and issue report agelinas. I'll check all those questions as soon as possible.

**Comment by tomdyson** [comment]
@agelinas in case you missed it, 0.2 of this excellent module now supports StreamField.

**Comment by rmartins90** [comment]
It now supports InlinePanels with no problem. Thanks for reporting it.

**Comment by agelinas** [comment]
Thank you for the excellent work! I've installed 0.2 yesterday and will experiment using Streamfields again.

**Comment by SalahAdDin** [comment]
I have the same problem now: see here please https://github.com/infoportugal/wagtail-modeltranslation/issues/22
:-1:
