### ISSUE TITLE
Improve unit testing

### ISSUE THREAD

**Issue by Alexandre27** [infoportugal/wagtail-modeltranslation#104]
Increase the coverage of unit testing, as of now only a small portion of features are tested. There are no tests for the patched Page functions, and panel patching methods lack some more advanced tests.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by dmarcelino** [comment]
Since March 2017 the unit test count and coverage increased considerably. If a particular method is lacking tests it's probably best to raise an issue targetting it specifically.
