### ISSUE TITLE
WagtailTranslationOptions doesn't find all Page models

### ISSUE THREAD

**Issue by dwasyl** [infoportugal/wagtail-modeltranslation#106]
In 0.6rc1, the new `WagtailTranslationOptions` applies the standard base fields to any model that derives from `Page`. However, I noticed a model that had multiple inheritances (specifically a form based on `WagtailCaptchaEmailForm` which is based on `AbstractEmailForm` which is based on `AbstractForm` which is based on `Page`), wasn't picked up by if options.

On Python 2.7, Django 1.8.13, `model.__bases__` only returns the direct parent of the Page model. I added `or Page in model._meta.get_parent_list()` which solved my problem.

So the entire if statement in WagtailTranslationOptions could read:
` if Page in model.__bases__ or Page in model._meta.get_parent_list():`

Or, perhaps there's a better way to get the base class of a model?

**Comment by pyMan** [comment]
I think `issubclass(model, Page)` should do the job

**Comment by dwasyl** [comment]
Oh, yes, that's a more elegant solution and seems to do the trick.

**Comment by DiogoMarques29** [comment]
Hello,
Thanks for this patch, but we are trying a new approach on the experimental branch that we think solves this and many other problems.
