### ISSUE TITLE
Translating other (non-standard) models with panels

### ISSUE THREAD

**Issue by dwasyl** [infoportugal/wagtail-modeltranslation#108]
Perhaps I'm one of the few doing this, but I'm using `wagtail` with `wagtailmenus`, a great package. However, even if the `MainMenuItem` and `FlatMenuitem` models are tagged for translation, the multi-language fields do not show up in Wagtail Admin.

This is because `patch_wagtail_models()` in `patch_wagtailadmin.py` only runs on models deriving from `Page`, or a registered snippet or a `BaseSetting`. Other models that may have panels registered, but they won't be picked up.

So far, the only way I've found to deal with this is to manually run WagtailTranslator on the models in question. This solution works fine, but is quite clunky and not glaringly obvious to most people.

I would suggest finding a way to flag other models, or check every registered models for associated panels?

That said, I haven't yet figured out how to get the `Site` model to appear with translated fields in Wagtailadmin (for it's name). The model doesn't see mot have a panel to monkey patch.

**Comment by dmarcelino** [comment]
Hi @dwasyl , going through [patch_wagtailadmin.py#L110-L121](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/patch_wagtailadmin.py#L110-L121) I can see `_patch_other_models()` was added to deal with models that don't subclass `Page`:

```python
    def _patch_other_models(self, model):
        if hasattr(model, 'edit_handler'):
            edit_handler = model.edit_handler
            for tab in edit_handler:
                tab.children = self._patch_panels(tab.children)
        elif hasattr(model, 'panels'):
            model.panels = self._patch_panels(model.panels)

        if model in get_snippet_models() and model in SNIPPET_EDIT_HANDLERS:
            del SNIPPET_EDIT_HANDLERS[model]
        else:
            get_setting_edit_handler.cache_clear()
```

Can you please try reproducing this issue with latest version from master branch? (Please note v0.8 introduces some breaking changes and requires some changes: https://github.com/infoportugal/wagtail-modeltranslation#upgrade-considerations-v08)

**Comment by dmarcelino** [comment]
Closing this issue as stale, please reopen if you have further queries.

**Comment by Ramblurr** [comment]
@dwasyl  Can I ask how you managed to succesfully generate the `*_lang` migrations for `MainMenuItem`?

I've added the following to `myapp/translation.py`

```python
from wagtailmenus.models.menuitems import MainMenuItem

@register(MainMenuItem)
class MainMenuItemTR(TranslationOptions):
    fields = [
        "link_text",
    ]
```

When I run makemigrations, it creates the migration file inside the venv (e.g., `./venv/lib/python3.7/site-packages/wagtailmenus/migrations/0024_auto_20200608_1006.py). This obviously isn't good.

Any tips on how I can get this migration to be output into my own apps migration folder?
