### ISSUE TITLE
"Live" hyperlink doesn't work on admin interface

### ISSUE THREAD

**Issue by tiagofmc** [infoportugal/wagtail-modeltranslation#109]
When clicking the "Live" button on the admin interface, the slug is 'None', and doesn't redirect to the correspondent page.

**Comment by dmarcelino** [comment]
Hi @tiagofmc, I'm unable to reproduce this issue using v0.8 (latest in `master`).

Can you please try reproducing this with latest version from `master` branch? Please note `v0.8` introduces some breaking changes and requires some changes: https://github.com/infoportugal/wagtail-modeltranslation#upgrade-considerations-v08

**Comment by dmarcelino** [comment]
Closing this issue as stale, please reopen if you have further queries.

**Comment by tiagofmc** [comment]
Hello @dmarcelino.

Sorry, the problem was indeed solved, just forgot to reply.

Thanks!

**Comment by dmarcelino** [comment]
Good to hear it's solved.
