### ISSUE TITLE
Url missing

### ISSUE THREAD

**Issue by fproldan** [infoportugal/wagtail-modeltranslation#111]
Hi! I'am using this library (0.6.0rc1) with django==1.10.7, wagtail==1.9 and python 2.7.12.
When i create a new page the url is not setted.
I can create a page and after register it using WagtailTranslationOptions, do makemigrations and migrate and it's works, but after this, if i create another page, the url is not setted.

Any ideas?

Thanks

**Comment by jorenham** [comment]
Same issue for wagtail-modeltranslation==0.6rc2, django==1.11, wagtail==1.12.3 and python 3.6

**Comment by dmarcelino** [comment]
@fproldan , @jorenham, I'm not sure I understand the issue. Just to be sure we are on the same page:

1. You create a new model which subclasses `Page`
2. Register the page with `WagtailTranslationOptions`
3. Run `makemigrations` and `migrate`

The above work. When you create a another model subclassing `Page`, are you repeating the above steps? Or doing something different?

Can you please try reproducing this issue with latest version from `master` branch? Please note `v0.8` introduces some breaking changes and requires some changes: https://github.com/infoportugal/wagtail-modeltranslation#upgrade-considerations-v08

**Comment by dmarcelino** [comment]
Closing this issue as stale, please reopen if you have further queries.
