### ISSUE TITLE
Error 500 on slug field validation

### ISSUE THREAD

**Issue by pyMan** [infoportugal/wagtail-modeltranslation#112]
With the release 0.6.0rc1 I still have the issue #98 that should instead have been fixed (create a page with slug X, then create another sibling page with same slug)

I saw some changes in the monkey patched `_validate_slugs`. I think it was best the previous version because the current one can't get siblings on pages being created, so no real check can be made. The previous version started looking for allowed_siblings (instead just actual siblings), so it could get some pages to check slugs with.

**Comment by DiogoMarques29** [comment]
Please re-open if the problem persists.
