### ISSUE TITLE
Can't makemigrations or runserver

### ISSUE THREAD

**Issue by zoro1666** [infoportugal/wagtail-modeltranslation#121]
Hi, I'm trying to use this library and the instructions were straightforward, but I got this error,

`from wagtail.wagtailadmin.views.pages import get_page_edit_handler,\
ImportError: cannot import name 'get_page_edit_handler'`

what is this? what to do in this case?

`
Django==1.11.1
wagtail==1.10.1
wagtail-modeltranslation==0.4.4`

with Python 3.6.1

Thanks

**Comment by Wladislav** [comment]
File "c:\dagcoin\coinvenv\lib\site-packages\wagtail_modeltranslation\models.py", line 16, in <module>
    from wagtail.wagtailadmin.views.pages import get_page_edit_handler,\
ImportError: cannot import name 'get_page_edit_handler'

Help!

**Comment by mixxorz** [comment]
I actually wouldn't recommend that you use the version released on pypi as it's pretty old. Instead try release 0.6.0rc2. We've been using it for a month now in production and its pretty stable.

https://github.com/infoportugal/wagtail-modeltranslation/releases/tag/v0.6.0rc2

**Comment by zoro1666** [comment]
@mixxorz thanks man, i changed to the default django translation.

**Comment by SalahAdDin** [comment]
@mixxorz does it works with latest `wagtail` version?

**Comment by mixxorz** [comment]
@SalahAdDin Yes it does.
