### ISSUE TITLE
Documentation: TranslationOptions

### ISSUE THREAD

**Issue by agelinas** [infoportugal/wagtail-modeltranslation#126]
## I like wagtail-modeltranslation...

I have been testing wagtail-modeltranslation from the beginning, but had not been able to get it to work for me for a long time (about a year). But yesterday I installed version 0.6.0rc2 and managed to get it running, but this version started working only when I imported TranslationOptions instead of WagtailTranslationOptions (which could not be found).

```
# translation.py
from .models import HomePage
from wagtail_modeltranslation.translation import TranslationOptions
from modeltranslation.decorators import register

@register(HomePage)
class HomePageTR(TranslationOptions):
    fields = (
        'body',
        'title',
    )
```

I am using Django 1.11.4 and Wagtail 1.12

Thank you for everyone who work on this project.

**Comment by xintellion** [comment]
Hi what error did you get on using WagtailTranslationOptions?

**Comment by agelinas** [comment]
I got the same message, which contained Page not registered. It is working fine now, using TranslationOptions instead of WagtailTranslationOptions. I don't know about your fix... I'll do more testing. Maybe the developper will have an explanation. This is a RC2, so there might be a few things to tweek.

**Comment by xintellion** [comment]
There is 
```
@register(Page)
class PageTR(TranslationOptions):
    pass
```
which registers the page for translation. But you're right it should work without explicitly importing wagtail_modeltranslation.translation.

**Comment by agelinas** [comment]
Had problems again using translation.py file example:

```
from .models import Foo
from wagtail_modeltranslation.translator import WagtailTranslationOptions
from modeltranslation.decorators import register

@register(Foo)
class FooTR(WagtailTranslationOptions):
    fields = (
        'body',
    )
```
I changed the import: 
**from modeltranslation.decorators import register**
TO
**from wagtail_modeltranslation.translation import register**

and it's working fine now. 

Maybe the documentation needs to be updated...

`

**Comment by dmarcelino** [comment]
@agelinas, @DiogoMarques29 I believe PR  #137 has fixed all standing issues addressed here.
