### ISSUE TITLE
RemovedInWagtail113Warning

### ISSUE THREAD

**Issue by Qurus** [infoportugal/wagtail-modeltranslation#128]
Hi I have installed and followed installation progress. But makemigrations giving this error 

RemovedInWagtail113Warning: <class 'wagtail.wagtailcore.models.Page'>.relative_url should accept a 'request' keyword argument. See http://docs.wagtail.io/en/v1.11/reference/pages/model_reference.html#wagtail.wagtailcore.models.Page.relative_url
  RemovedInWagtail113Warning)

wagtail-modeltranslation==0.6.0rc2
Django==1.11.5
wagtail==1.12.2

**Comment by dmarcelino** [comment]
Fixed by PR #125.
