### ISSUE TITLE
change_lang returns None

### ISSUE THREAD

**Issue by ArieVanE** [infoportugal/wagtail-modeltranslation#13]
I'm using the wagtail demo and I have made the HomePage translatable according your instructions. In the admin this works fine.

Now I amended the home_page.html template with this:

    {% load modeltranslation %}
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" data-hover="dropdown" href="#">{{     LANGUAGE_CODE }}<i class="fa fa-angle-down ml5"></i></a>
        <ul class="dropdown-menu" id="language-dropdown">
            {% for lang in languages %}
                {% if lang.0 != LANGUAGE_CODE %}
                    <li tabindex="-1"><a href="{% change_lang lang.0 %}">{{ lang.1 }}</a></li>
                {% endif %}
            {% endfor %}
       </ul>
    </li>

To make sure that languages has a value I wrote a tiny context processor:

    from django.conf import settings

    def languages(request):

        return {'languages': settings.LANGUAGES}

And settings.LANGUAGES is defined like this (in compliance with the instructions from django-model-translation):
    gettext = lambda s: s
    LANGUAGES = (
        ('en', gettext('English')),
        ('nl', gettext('Dutch')),
        ('bg', gettext('Bulgarian')),
   ) 

Unfortunately this doesn't seem the way to do it, because the returned urls are None, for example:

    <li tabindex="-1"><a href="None">Dutch</a></li>
    <li tabindex="-1"><a href="None">Bulgarian</a></li>

What am I doing wrong?

**Comment by rmartins90** [comment]
Hi ArieVanE, we've been very busy, we just released a new version with support for StreamFields, and fix some small issues.
We'll look at your problem very soon.

**Comment by pymarco** [comment]
Thanks for creating this app!

Unless I'm missing something, the `templatetags` directory is not included from `pip install wagtail-modeltranslation`

```
~/.virtualenvs/wagtail.trans/lib/python2.7/site-packages/wagtail_modeltranslation
$: ls -l
-rw-rw-r-- 1 pymarco pymarco   335 Aug  7 15:05 apps.py
-rw-rw-r-- 1 pymarco pymarco   837 Aug  7 15:05 decorators.py
-rw-rw-r-- 1 pymarco pymarco 16968 Aug  7 15:05 fields.py
-rw-rw-r-- 1 pymarco pymarco  1353 Aug  7 15:05 forms.py
-rw-rw-r-- 1 pymarco pymarco   213 Aug  7 15:05 __init__.py
drwxrwxr-x 3 pymarco pymarco  4096 Aug  7 15:05 management
-rw-rw-r-- 1 pymarco pymarco 20995 Aug  7 15:05 manager.py
-rw-rw-r-- 1 pymarco pymarco 15422 Aug  7 15:05 models.py
-rw-rw-r-- 1 pymarco pymarco  2891 Aug  7 15:05 settings.py
drwxrwxr-x 3 pymarco pymarco  4096 Aug  7 15:05 static
-rw-rw-r-- 1 pymarco pymarco   356 Aug  7 15:05 translation.py
-rw-rw-r-- 1 pymarco pymarco 24296 Aug  7 15:05 translator.py
-rw-rw-r-- 1 pymarco pymarco  5539 Aug  7 15:05 utils.py
-rw-rw-r-- 1 pymarco pymarco   676 Aug  7 15:05 wagtail_hooks.py
-rw-rw-r-- 1 pymarco pymarco  4065 Aug  7 15:05 widgets.py
```

When I use git to clone the app from GitHub, the file structure includes a templatetags directory

```
~/Downloads/wagtail_modeltranslation
[master] $: ls -l 
-rwxrwxr-x 1 pymarco pymarco   335 Aug  7 16:41 apps.py
-rwxrwxr-x 1 pymarco pymarco   837 Aug  7 16:41 decorators.py
-rwxrwxr-x 1 pymarco pymarco 16968 Aug  7 16:41 fields.py
-rwxrwxr-x 1 pymarco pymarco  1353 Aug  7 16:41 forms.py
-rwxrwxr-x 1 pymarco pymarco   213 Aug  7 16:41 __init__.py
drwxrwxr-x 3 pymarco pymarco  4096 Aug  7 16:41 management
-rwxrwxr-x 1 pymarco pymarco 20995 Aug  7 16:41 manager.py
-rwxrwxr-x 1 pymarco pymarco 15422 Aug  7 16:41 models.py
-rw-rw-r-- 1 pymarco pymarco  8015 Aug  7 16:41 models.pyc
-rwxrwxr-x 1 pymarco pymarco  2891 Aug  7 16:41 settings.py
drwxrwxr-x 4 pymarco pymarco  4096 Aug  7 16:41 static
drwxrwxr-x 2 pymarco pymarco  4096 Aug  7 16:41 templatetags <--- Template tags directory
-rw-rw-r-- 1 pymarco pymarco    16 Aug  7 16:41 tests.py
-rw-rw-r-- 1 pymarco pymarco   356 Aug  7 16:41 translation.py
-rwxrwxr-x 1 pymarco pymarco 24296 Aug  7 16:41 translator.py
-rwxrwxr-x 1 pymarco pymarco  5539 Aug  7 16:41 utils.py
-rw-rw-r-- 1 pymarco pymarco   676 Aug  7 16:41 wagtail_hooks.py
-rwxrwxr-x 1 pymarco pymarco  4065 Aug  7 16:41 widgets.py
```

**Comment by pymarco** [comment]
ArieVanE, your context processor is unneeded. In your template you can use

```
{% load i18n %}
{% get_available_languages as LANGUAGES %}
{% get_current_language as LANGUAGE_CODE %}
```

But how to switch languages as you are trying to do is something I am yet to learn. Hopefully soon though

**Comment by pymarco** [comment]
ArieVanE, to switch languages from a dropdown you can follow the tutorial at this link. It worked for me.

http://machakux.appspot.com/blog/17010/django_using_i18n_patterns_and_locale_switcher

**Comment by rmartins90** [comment]
This was fixed here https://github.com/infoportugal/wagtail-modeltranslation/pull/32
