### ISSUE TITLE
Copy button should use POST not GET

### ISSUE THREAD

**Issue by kakulukia** [infoportugal/wagtail-modeltranslation#132]
The copy from language button is using the URI to actually copy the page contents which causes a normally configured webserver to deny the request, because the resulting URI gets very large very quick due to urlencoding of plain HTML as it seems. 
In my case for a normal page with some content elements it results in an URl thats 34735 chars long. Way too long for any server with ts default config.

This shouldbe altered so that at least a not so restrictive POST request is used instead of GET with insanly large URIs.

**Comment by stuaxo** [comment]
Probably worth changing the title to something boring like

"Copy button should use POST not GET" 

so someone scanning the buglist is more likely to read this.

**Comment by DiogoMarques29** [comment]
Fixed.

**Comment by stuaxo** [comment]
OT:  Seeing all these wagtail fixes, while my current work project is on a certain other well known CMS that runs on Django 😢

**Comment by kakulukia** [comment]
It took some time tho - @DiogoMarques29 what about compatibility with Djangos Sites framework - is that taken care of already, not sure which ticket that was ..

**Comment by DiogoMarques29** [comment]
No @kakulukia 
This packages is intended to patch django-modeltranslation into wagtail. There are no plans into making it work for multisite. 
Please take a look at: https://github.com/wagtail/wagtailtrans

**Comment by kakulukia** [comment]
never mind
