### ISSUE TITLE
No module named 'wagtail_modeltranslation'

### ISSUE THREAD

**Issue by heaversm** [infoportugal/wagtail-modeltranslation#136]
Getting error `ModuleNotFoundError: No module named 'wagtail_modeltranslation'`. 

Have:

```
INSTALLED_APPS = [
  ...
  'wagtail_modeltranslation'
]
```

in `base.py` of wagtail, and

```
wagtail-modeltranslation==0.4.4
```

in `requirements.txt`.

Have run `pip install wagtail-modeltranslation` and followed all requirements up to that point.

Noticed that the installed app uses `_` but requirements / pip install uses `-`

**Comment by benjaoming** [comment]
Can you do this?

```
$ python
>>> import wagtail_modeltranslation
```

If not, check that your virtualenv is active...

**Comment by dmarcelino** [comment]
Closing this issue as stale, please reopen if you have further queries.
