### ISSUE TITLE
Original slug field language changes depending on editor's language

### ISSUE THREAD

**Issue by dmarcelino** [infoportugal/wagtail-modeltranslation#141]
Hi there,

I've noticed this issue when, by accident, I was using Wagtail admin's interface in the non-default language of my project and later noticed that my `{% slugurl 'slug_value' %}` statements ceased to work. Steps to reproduce this issue:

### 1. Using wagtail's admin interface in English

Save a page with `slug_en='english'` and `slug_en='portuguese'`.

Any declarations of `{% slugurl 'english' %}` will work in either language. In the database   `wagtailcore_page.slug` should read `'english'`.

### 2.  Using wagtail's admin interface in a different language (Portuguese for example)

Save the same page with exactly the same slugs (`slug_en='english'` and `slug_en='portuguese'`).

Declarations of `{% slugurl 'english' %}` break in both languages and `wagtailcore_page.slug` reads `'portuguese'`.

The behaviour above is consistent with `django-modeltranslation`'s [State of the Original Field](http://django-modeltranslation.readthedocs.io/en/latest/usage.html#the-state-of-the-original-field) but if editors of different languages are using/translating a wagtail website they will likely break any links relying on  `{% slugurl 'slug_value' %}`.

I suggest `wagtail-modeltranslation` works around this `django-modeltranslation` limitation and enforces a consistent slug value in the DB.

**Comment by dmarcelino** [comment]
Hi @DiogoMarques29, @Alexandre27, 

Please take a look at PR  #142 which offers a solution for this issue.

I've spent a couple of days looking for a fix and this was the most elegant one I could find. Feel free to ask any questions and/or offer suggestions.

Hey @WnP, I've noticed your fix to `_new_relative_url()`. Any chance you can take a look and perhaps test my changes from PR  #142?

Thanks

**Comment by DiogoMarques29** [comment]
Thanks! Great work!
