### ISSUE TITLE
Issues saving pages from admin editor on v0.8a1

### ISSUE THREAD

**Issue by timstallmann** [infoportugal/wagtail-modeltranslation#166]
I upgraded to the new version and it is working so much better than previously; except for the following situation:

1. I run the initial `sync_page_translation_fields` command, so now I have blank `_en`/`_es` fields in all my pages, and the slugs are also blank.
2. I go to edit a page and fill in slug/title/body fields in both Spanish and English.
3. When saving, I get two errors:
(1) `AttributeError: 'BasePageManagerFromPageQuerySet' object has no attribute 'rewrite'` -- tracing back to line 361 in `patch_wagtailadmin.py`
and (2) `TypeError: object of type 'NoneType' has no len()` -- tracing back to line 367 in the same file.

**Comment by timstallmann** [comment]
The code in #167 seems to be fixing these two errors for me locally, but I don't know enough about the codebase yet to know if that really is the right approach...

**Comment by dmarcelino** [comment]
Hi @timstallmann, 

I'm glad things are working better. 🙂 

Did you run `python manage.py update_translation_fields` after installation? You need that to populate the translated fields. More about it at `django-modeltranslation` docs: http://django-modeltranslation.readthedocs.io/en/latest/commands.html#the-update-translation-fields-command

**Comment by timstallmann** [comment]
Aha! Thanks so much for the clarification!

I was getting errors running `update_translation_fields` also related to the `rewrite()` call. Forcing install of the latest version of `django-modeltranslation` via 
this line in `requirements.txt` fixed the problems `-e git+https://github.com/deschler/django-modeltranslation@master#egg=django-modeltranslation`.

Maybe the need for this specific dev version of `django-modeltranslation` could be specified in the docs? I'm happy to make a PR to update docs if that would help..

**Comment by dmarcelino** [comment]
> I'm happy to make a PR to update docs if that would help..

Yeah, that sounds good to me, thanks.

**Comment by dmarcelino** [comment]
Closing this since `v0.8` has been released (#168) and everything should now work out of the box. Make sure `django-modeltranslation` v0.12.2 is installed, that is now a hard requirement.

**Comment by timstallmann** [comment]
Yay!
