### ISSUE TITLE
support for wagtail 2?

### ISSUE THREAD

**Issue by richtier** [infoportugal/wagtail-modeltranslation#169]
I'm running wagtail 2. Is support for wagtail 2 on the roadmap?

Problems include the fact the import paths for wagtail 2 have changed since wagtail 1. i.e.,

`from wagtail.wagtailcore.models import Page` is now `from wagtail.core.models import Page`

**Comment by dmarcelino** [comment]
Supporting Wagtail 2 is certainly desirable and ideally we should keep support for previous versions.

@richtier, are the different paths the only issue? Are you up for submitting a PR?

**Comment by richtier** [comment]
@DiogoMarques29 I will investigate further and submit a PR over a next few days

**Comment by stuaxo** [comment]
Mostly the moved imports are the difference, these are some to get started -

wagtail 1.x | wagtail 2.x
-- | --
wagtailacore | core
wagtailimages | images
wagtailsearch | search
wagtailsnippets | snippets

Some other projects put them behind a ```try/except ImportException``` with wagtail2 first.

**Comment by agelinas** [comment]
Wagtailmenus has recently been patched to support Wagtail 1.x and 2.x, as well as Django 2.x. Using their methodology, I could work on applying the required changes to Wagtail Modeltranslation if no one has started working on it. Also this would need to be documented, which I could also do.

**Comment by stuaxo** [comment]
Sounds good to me - here are patches to some other projects to get them working on wagtail 2 in this way

wagtail-bakery
https://github.com/moorinteractive/wagtail-bakery/pull/27/files

wagtail-svgmap
https://github.com/City-of-Helsinki/wagtail-svgmap/pull/14/files

wagtail-markdown
https://github.com/torchbox/wagtail-markdown/pull/31/commits/3762b437a4999985974769de9c4e9272aabd83ba

**Comment by stuaxo** [comment]
This list of installed apps between 1 + 2 is pretty handy

https://github.com/stuaxo/wagtail-svgmap/blob/57730f1011061c02b22e115ede66f2935a75b459/wsm_test/settings.py

**Comment by stuaxo** [comment]
@agelinas how far did you get?   
Sorry to be a pain, I needed to try and see if this was possible a bit sooner than I thought I would, so started a quick port here -

https://github.com/infoportugal/wagtail-modeltranslation/pull/180

It's mostly working, just trying to work out what makemigrations is complaining about.

**Comment by agelinas** [comment]
@stuaxo 

I have tried making wagtail-modeltranslation compatible with WT2, but have run into similar roadblocks as you are running into. I am not a developer, so I can't be counted on to investigated technical issues. Also, since WMT relies on django-modeltranslation, I have also had some errors that occured from that piece of software, but I imagine that it's because of something that WT-modeltranslation is sending it.

Tomorrow I can test what you have done and compare with what I have done. Maybe we can get help by posting the errors we are getting but for now, I have to verify all the modifications I've done and pin point where the problem(s) are.

And I wonder how stable is WT-Modeltranslation 0.8? Good luck.

**Comment by stuaxo** [comment]
Ok, let's see how far we can get.

I think mine is having trouble with django 2, however wt2 works with django 1.x so I might separate django 2 from wt2

**Comment by agelinas** [comment]
Sorry, what seemed a simple tweeking of the code just got too complicated for me as I do not have the required knowledge and skills, but I see that you are making progress and getting help. Thank you very much!

**Comment by stuaxo** [comment]
No probs, the pointer to django-modeltranslation is handy.     It was more involved than I thought as well.
Going to test it a bit more in the next few days - it seems to work with wt2, just not with django 2 yet.

**Comment by dmarcelino** [comment]
@DiogoMarques29, it's worth considering a new release so the Wagtail2 folks can benefit from `wagtail-modeltranslation`. Looking at the pending PRs the only one I would try to include in such release is PR #178.

Cheers

**Comment by DiogoMarques29** [comment]
@dmarcelino 
I've merged the PR and now we are ready to do a new release.

Cheers

**Comment by dmarcelino** [comment]
Awesome @DiogoMarques29!
