### ISSUE TITLE
Translating snippet fields

### ISSUE THREAD

**Issue by jorenham** [infoportugal/wagtail-modeltranslation#183]
I have a snippet 

```python
# models.py
@register_snippet
class Foo(models.Model):
    bar = models.CharField(max_length=255)

    def __str__(self):
        return self.bar
```

which I registered with

```python
#translation.py
@register(models.Foo)
class FooTranslationOptions(TranslationOptions):
    fields = ('bar', )
```

and I synced the fields with

```bash
./manage.py sync_translation_fields
./manage.py sync_page_translation_fields
```

But in the snippet listing in the wagtail admin (`localhost:8000/wagtail_admin/snippets/myapp/foo/`) the names are not displayed and the items not clickable:
![selection_099](https://user-images.githubusercontent.com/6208662/37054381-00f4e8ce-217f-11e8-8a92-da86bca6fc66.png)

**Comment by dmarcelino** [comment]
Hi @jorenham, I never used `snippets` but don't you have to define `panels`? At least that's what the Wagtail docs [suggest](http://docs.wagtail.io/en/latest/topics/snippets.html#snippet-models). And also the `wagtail-modeltranslation` tests: [tests/models.py#L54-L60](https://github.com/infoportugal/wagtail-modeltranslation/blob/06fd1e8bfa3aa69ad89097107084a6e9757226b8/wagtail_modeltranslation/tests/models.py#L54-L60).

Also, any reason for using `./manage.py sync_translation_fields`? Generally it's better to use django migrations for managing translation fields for your own models.

**Comment by jorenham** [comment]
@dmarcelino I left out the `panels` for brevity. And I ran `sync_translation_fields` only after I did the regular `migrate.

**Comment by jorenham** [comment]
I managed to solve the issue by running `manage.py update_translation_fields`
