### ISSUE TITLE
Added modeltranslation, but can't find my initial content

### ISSUE THREAD

**Issue by stuaxo** [infoportugal/wagtail-modeltranslation#190]
Hi,
   I've added wagtailmodeltranslation to my site that already has a lot of content.   However, I can't find it under any of the languages.

Assuming I've done something silly ?

Cheers
S

**Comment by dmarcelino** [comment]
Hey @stuaxo,

Did you follow the [Quick Start](https://github.com/infoportugal/wagtail-modeltranslation#quick-start)? And more specifically did you run `update_translation_field` at the end?

Cheers

**Comment by stuaxo** [comment]
I'll double check..

**Comment by stuaxo** [comment]
Great, that was it.

Apologies for all the n00b questions, I've been learning wagtail, porting some things to wagtail 2 all while trying to get a project working that has an only just-about-doable deadline.    :sweat_smile:

**Comment by dmarcelino** [comment]
No worries @stuaxo, good luck to your project.
