### ISSUE TITLE
v0.10 Proposal

### ISSUE THREAD

**Issue by dmarcelino** [infoportugal/wagtail-modeltranslation#191]
Hey fellas,

As we know `django-modeltranslation` doesn't currently support Django 2, but when it does, and when we integrate it I suggest we drop support for older versions of Wagtail. We currently support 3 LTS versions (1.4, 1.8 and 1.12) and I suggest we cut it down to 2 LTS versions, in other words v1.8+. This will make it easier to support `wagtail-modeltranslation` and the tests will run faster.

In summary:

- [x] Add support for Django 2 (depends on `django-modeltranslation`, see deschler/django-modeltranslation#436 and deschler/django-modeltranslation#457)
- [x] Remove support for Wagtail < 1.8 from `travis.yml` and `setup.py`
- [x] Remove try/except when importing `VERSION` ([runtests.py#L8-L11](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/runtests.py#L8-L11), [tests.py#L14-L17](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/tests/tests.py#L14-L17))
- [x] Remove special `WAGTAIL_APPEND_SLASH` import for Wagtail<1.5 ([patch_wagtailadmin.py#L48](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/patch_wagtailadmin.py#L48)) introduced in PR #197
- [x] remove support for django < 1.8 (last version supported by Wagtail  1.8)

@DiogoMarques29, @tiagofmc, @Alexandre27  would love to hear your opinion on this.

Cheers

**Comment by Alexandre27** [comment]
Hi @dmarcelino,

Seems like a good proposal to me, the current version is stable enough to work with previous versions of Wagtail and Django and I think that the workarounds needed to keep it compatible with the older versions make the code a lot harder to maintain and debug as you have multiple flows for the same thing. Supporting 2 LTS seems more than enough (django-rest-framework, for example, only supports django 1.10, 1.11 and 2.0).

Cheers

**Comment by DiogoMarques29** [comment]
Olá @dmarcelino 
I have released version 0.9 just now by mistake, should have released 0.8.2.
Should we change the title to a v1 ?

Cheers

**Comment by dmarcelino** [comment]
Bom dia @DiogoMarques29,

I'm not sure we reached `1.0` status yet... Perhaps `0.10`?

Cheers

**Comment by DiogoMarques29** [comment]
Agree @dmarcelino , 0.10 is better! :)

**Comment by dmarcelino** [comment]
`0.10` it is 👍

**Comment by dmarcelino** [comment]
Olá @Alexandre27 e @DiogoMarques29,

django-modeltranslation has released the beta version for `0.13` with Django 2 support (https://github.com/deschler/django-modeltranslation/issues/457#issuecomment-381596104).

As such I've integrated django-modeltranslation `0.13b1` on [wagtail-modeltranslation/django2 branch](https://github.com/infoportugal/wagtail-modeltranslation/tree/django2), removed support for Wagtail<1.8 and bumped the version to `0.10b1` (since django-modeltranslation is still in beta). And it passes all tests ([`django2` travis build](https://travis-ci.org/infoportugal/wagtail-modeltranslation/builds/370662772?utm_source=github_status&utm_medium=notification)).

Feel free to give it a spin. Whenever you feel it's ready to be integrated in `master` I'll submit a PR.

cc @stuaxo

**Comment by stuaxo** [comment]
Cheers for the headsup, I'll definitely be trying version 0.9, probably won't get time to try the django 2 support, as moving on to some non-wagtail based projects.

**Comment by dmarcelino** [comment]
Olá @DiogoMarques29, please take a look at my previous comment and let me know if you think it's ready to be merged into `master`. Cheers

**Comment by DiogoMarques29** [comment]
Olá @dmarcelino, sounds good to me! The only thing missing is the documentation referring what versions of django/wagtail we support in this new 0.10 version. Can you add that and make a PR please?

Cheers

**Comment by sdonk** [comment]
Hi guys,
now that wagtail 2.4 [only supports Django 2](https://docs.wagtail.io/en/latest/releases/2.4.html#removed-support-for-django-1-11) is there any plan to release version `0.10` soon?

Cheers

**Comment by Pomax** [comment]
@DiogoMarques29 would it be possible to get 0.10 out, now that wagtail 2.4 is officially the new baseline?

**Comment by DiogoMarques29** [comment]
Hello
Since django-modeltranslation has not yet release version 0.13 (it's only in beta), version 0.10 of wagtail-modeltranslation will be release then. In the mean time, version 0.10b1 has been release and can now be installed through pypi.

Cheers

**Comment by dmarcelino** [comment]
Olá @DiogoMarques29, great job on merging `django2` branch and moving things forward, thanks! I haven't been very active on the `wagtail-modeltranslation` front as our project went live 2 weeks ago and I'm quite busy.

Anyway I've just noticed that `model-translation` released `0.13-beta3` on https://github.com/deschler/django-modeltranslation/issues/489#issuecomment-464508048 and thought of letting you guys know! They are aiming to push a final version in 3 days, it would be great if someone on this thread could give it a spin before release.

**Comment by DiogoMarques29** [comment]
Olá @dmarcelino 
We are currently using version 0.10b1 already on one of our websites, it's going great so far. We want to create a new 0.10b2 version when django-modeltranslation releases 0.13 and then release 0.10.

Cheers

**Comment by dmarcelino** [comment]
Hey @DiogoMarques29, in that case you'll be happy to know that partizan released `django-modeltranslation` `0.13` 8 hours ago:

> 
> 
> Released 0.13 on pypi! 🙆‍♂️

😃

**Comment by easherma** [comment]
@DiogoMarques29 so can this be merged in now?

**Comment by DiogoMarques29** [comment]
Hi guys,
v0.10 released!

Cheers
