### ISSUE TITLE
Is language selection always by slug ?

### ISSUE THREAD

**Issue by stuaxo** [infoportugal/wagtail-modeltranslation#194]
Is it possible to have ```/en/somepage```  ```/fr/somepage```    or similar schemes ?

I'm a bit unclear about what happens when the slug would be the same in two languages.

I'm replacing a site that has a url structure a bit like the above, it would be good to have something where I coming in with a url like the above changed the default language.

**Comment by stuaxo** [comment]
Great, this should probably be in the README, I guess something along these lines ?

```
# Language URLS

Wagtail ModelTranslation optionally lets you have different page slugs per language. 

URL patterns handled are by i18n_patterns, see https://docs.djangoproject.com/en/1.11/topics/i18n/translation/#language-prefix-in-url-patterns
```

**Comment by dmarcelino** [comment]
Hey @stuaxo, the README is a bit bloated as is, the [docs](http://wagtail-modeltranslation.readthedocs.io/) are a better place for it. And BTW `wagtail-modeltranslation` allows you to translate most (or all?) of the `Page` fields such as Title, Body, Slug, Page title (for SEO) and Search description. 

Regarding the URL patterns bit, I'm not sure we need to cover it here, it's already handled by both Wagtail (see http://docs.wagtail.io/en/v2.0/advanced_topics/i18n/) and Django.

Anyway, feel free to make a PR to improve the docs.

**Comment by stuaxo** [comment]
Cheers, I'll close this for now + possibly come up with a patch.
