### ISSUE TITLE
Best way of finding if a page exists at a path ?

### ISSUE THREAD

**Issue by stuaxo** [infoportugal/wagtail-modeltranslation#198]
In a ClassBasedView I'm trying to determine if a page exists at a path (before I redirect to it) - whats the best way of doing this supporting different language slugs ?

So far I have this, which doesn't take different language slugs into account:
```
    def page_exists(self, path):
        path_components = [
            component for component in path.split('/') if component
        ]
        try:
            # Check validity by attempting to fetch page
            request = self.request
            page, args, kwargs = \
                request.site.root_page.specific.route(request, path_components[1:])  # noqa

            return True
        except Http404:
            pass

        return False
```

**Comment by dmarcelino** [comment]
Hi @stuaxo,

The simplest way to cover all languages for anything is to use the following pattern:

```python
from modeltranslation import settings as mt_settings
from django.utils.translation import get_language, trans_real


# Save the current active language
current_language = get_language()

for language in mt_settings.AVAILABLE_LANGUAGES:
    trans_real.activate(language)
    # do what you would normally do

# Re-enable the original language
trans_real.activate(current_language)
```

You can see a real example at [patch_wagtailadmin.py#L333-L353](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/patch_wagtailadmin.py#L333-L353).

Be careful with any exceptions that may be triggered as you don't want to accidentally change the current language.

**Comment by dmarcelino** [comment]
Closing this as inactive, please reopen if the issue persists of you have any update.
