### ISSUE TITLE
Migration problems with 1.0

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#20]
Hi guys, i like your project and i want help you with anyone thing that i can.

First, i have this problem yesterday installing your app and wagtail and migrate this apps, you can see all here:
https://groups.google.com/forum/#!topic/wagtail/TGdMze3Z8_s

The problem is with the fields that create your apps, if i understand good.

Please see the github issue, they blocked my issue :'(

**Comment by rmartins90** [comment]
Hi SalahAdDin.
As far as I can understand your problems started when you upgraded to Wagtail 1.0 right?

**Comment by SalahAdDin** [comment]
I don't know, i was working with 8.0 but i haven't installed modeltranslation.
I upgrade to 1.0 and install modeltranslation.
I think that this problem begin with model translation, see my comments in the github thread please.

**Comment by rmartins90** [comment]
fixed with 59bc9e5
