### ISSUE TITLE
Can't install 0.9.0 from pip

### ISSUE THREAD

**Issue by stuaxo** [infoportugal/wagtail-modeltranslation#203]
On django==1.11.11

It's weird as wtmt 0.9.0 seems to be listed on pypi

```  pip install wagtail-modeltranslation==0.9.0
Collecting wagtail-modeltranslation==0.9.0
  Could not find a version that satisfies the requirement wagtail-modeltranslation==0.9.0 (from versions: 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0a0, 0.5.0a1, 0.6.0rc1, 0.6.0rc2, 0.8a1, 0.8, 0.8.1)
No matching distribution found for wagtail-modeltranslation==0.9.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by dmarcelino** [comment]
@kakulukia, @DiogoMarques29, is this something you can help with?

Tested on my setup and got the same error.

**Comment by kakulukia** [comment]
well, version 0.9.0 is only uploaded to pypi for Python2 and my guess is that you were trying to install under Python3, which wont work?

**Comment by stuaxo** [comment]
I was.

The previous version works on python3 though, so this one probably should too ?

**Comment by timstallmann** [comment]
Seeing this issue too :(. And seem to be stuck since `pip` thinks that v0.8.1 is incompatible with Wagtail 2.0..

**Comment by richtier** [comment]
as a workaround for python3 users you can do:

```
-e git+https://github.com/infoportugal/wagtail-modeltranslation.git@v0.9.0#egg=wagtail_modeltranslation
```

**Comment by stuaxo** [comment]
Cheers @richtier, I'll definitely do this for now, as it makes more sense than pointing at master.

**Comment by dmarcelino** [comment]
Hi @kakulukia, in previous releases versions for both python3 and python2 were uploaded. Can the absence of the Python3 version be a consequence of the changes made to the release process back in PR #200? Is there any additional step that must be done for uploading the Python3 version?

@DiogoMarques29, can you think of anything that you used to do in previous releases that wasn't done for `0.9.0`?

Also, I've noticed that `download_url` at [setup.py#L49](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/setup.py#L49) is pointing at an old version:

```python
download_url='https://github.com/infoportugal/wagtail-modeltranslation/archive/v0.8.tar.gz',
```

I believe we need to change it to something more dynamic like, for example:


```python
download_url='https://github.com/infoportugal/wagtail-modeltranslation/archive/v" + version + ".tar.gz',
```
Thanks

**Comment by dmarcelino** [comment]
Hi @kakulukia and @DiogoMarques29, any update on the above queries?

**Comment by kakulukia** [comment]
Well, im not totally sure how this version copilation works. What were the manual step you did before the automation? 

For me the setup.py bdist_wheel command always did build both versions, as long as there is no version minimum in setup.py.

**Comment by dmarcelino** [comment]
> Well, im not totally sure how this version copilation works. What were the manual step you did before the automation?

@DiogoMarques29, can you answer this?

**Comment by dmarcelino** [comment]
Hi @DiogoMarques29, @Alexandre27, any update on this?

**Comment by DiogoMarques29** [comment]
Hello guys!
Sorry for the delayed response.
It turns out that I need to run `python3 setup.py sdist upload` after the `make release` command to upload all files needed to pypi. `make release` only sends the necessary files for python 2 in my computer. @kakulukia maybe because my `python` command is a python2.7? 

Problem solved I believe. Can anyone confirm this please?

Cheers

**Comment by kakulukia** [comment]
That might be it. My default is Python3.

**Comment by stuaxo** [comment]
@DiogoMarques29 one way round this might be to use a python3 virtualenv, since it creates a python alias that will be python 3 in this case.

**Comment by DiogoMarques29** [comment]
yes @stuaxo , next time I release a new version I'll try that! thanks all!

**Comment by dmarcelino** [comment]
The python3 virtualenv sounds like the best option. Thanks for taking care of this @DiogoMarques29 👍
