### ISSUE TITLE
v.9: Streamfield is not supported by modeltranslation when combined with other applications

### ISSUE THREAD

**Issue by dwasyl** [infoportugal/wagtail-modeltranslation#204]
I'm running v.9, with `modeltranslation-0.12.2` also installed and everything works great - however, I installed `django-cities-light` (which relies on `django-autoslug` and now get non-stop `django.core.exceptions.ImproperlyConfigured: StreamField is not supported by modeltranslation.` errors when running the application.

Is there a way of letting applications that might rely on `modeltranslation` not to conflict with `wagtail-modeltranslation`?

**Comment by dmarcelino** [comment]
Hi @dwasyl, see https://github.com/infoportugal/wagtail-modeltranslation/issues/186#issuecomment-375268868. Please re-open if that doesn't solve your issue.
