### ISSUE TITLE
different tabs for each locale?

### ISSUE THREAD

**Issue by Pomax** [infoportugal/wagtail-modeltranslation#208]
I was wondering if there was a setting that organised the fields in a way that keeps everything from the main model in the primary content tab, but creates additional tabs for each set of localizable fields, so that you get something like this mockup, instead:

![image](https://user-images.githubusercontent.com/177243/40626902-617c81de-6270-11e8-8ba7-b7d2a428652a.png)

**Comment by dmarcelino** [comment]
Hi @Pomax, I'm closing this over #173 where a similar feature is being discussed. Please continue the discussion there.
