### ISSUE TITLE
volunteer to work on documentation

### ISSUE THREAD

**Issue by agelinas** [infoportugal/wagtail-modeltranslation#21]
Hi Rui,

I can help with the documentation, just let me know how I can help. I've started getting acquainted on how to create documentation with Readthedocs. Maybe Rui you have already something started which we could help with knowing that you are rather busy. 

I greatly appreciate wagtail-modeltranslation!

**Comment by rmartins90** [comment]
Hi agelinas, thanks for your support!
In fact I didn't start writing any documentation at all. Since this is a fork from django-modeltranslation you could grab some inspiration from their docs.

**Comment by agelinas** [comment]
Good suggestion about getting  inspiration from django-modeltanslation's documentation. Will start working on it. Have a great day!

**Comment by rmartins90** [comment]
Thanks!
Looking forward to see your work. We really appreciate all the contributions.
