### ISSUE TITLE
hiding "old" fields in non-Page models

### ISSUE THREAD

**Issue by Pomax** [infoportugal/wagtail-modeltranslation#210]
I tried using the library with a normal model that is used in Wagtail as a snippet, and while this works in terms of offering localized fields for anything that is marked as "has translations", it's showing some oddness.

Concretely, I have a `Petition` model that extends a `CTA` model, as followed:
```
class CTA(models.Model):
    name = models.CharField(
        default='',
        max_length=100,
        help_text='Identify this component for other editors',
    )

    header = models.CharField(
        max_length=500,
        help_text='Heading that will display on page for this component',
        blank=True
    )

    description = RichTextField(
        help_text='Body (richtext) of component',
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'CTA'


@register_snippet
class Petition(CTA):

    class Meta:
        verbose_name = 'petition snippet'
```
With the following addition to `translation.py`:
```
from .models import (
    # ...
    CTA,
    Petition,
)

from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register

@register(CTA)
class CTATR(TranslationOptions):
    fields = (
        'name',
        'header',
        'description',
    )

@register(Petition)
class PetitionTR(TranslationOptions):
    fields = (
    )
```

Running this through migrations, sync, and update, definitely works in terms of getting localized fields to show, but it doesn't "hide" the original fields the same way it does for Pages:

![image](https://user-images.githubusercontent.com/177243/41055333-d5f40e68-6975-11e8-8ef2-fcc810c4891b.png)

Compare this to how the Page gets changed:

![image](https://user-images.githubusercontent.com/177243/41055357-e9052622-6975-11e8-9d61-bbd5a390b71c.png)

Is there a way to make wagtail-modeltranslations to effect the same hiding of the original field for generic `Model` extensions as it does for Wagtail `Page`s?

**Comment by DiogoMarques29** [comment]
Hi @Pomax 
You need to define `panels` for CTA class like:
    panels = [
        FieldPanel('name'),
        FieldPanel('header'),
        FieldPanel('description'),
    ]

Cheers

**Comment by Pomax** [comment]
Hmm, that is not wagtail's requirement though, is it? I'd rather not starting putting code in generic Django models unless it's absolutely necessary, and adding them just to help wagtail-modeltranslation seems a bit odd. I would imagine that it would be able to automatically add those panels when it analyses the class to determine what to call all the localized fields, so that the original file doesn't need additional code?

**Comment by Pomax** [comment]
awesome, thanks so much!
