### ISSUE TITLE
ImportError: cannot import name 'Foo'

### ISSUE THREAD

**Issue by dinosaxon** [infoportugal/wagtail-modeltranslation#221]
Dear all

I have installed wagtail-modeltranslation and created the translation.py file. However, I get the error:

from .models import Foo
ImportError: cannot import name 'Foo'

Any help is appreciated.

Thank you

**Comment by DiogoMarques29** [comment]
Hi @dinosaxon 
That is only an example of how to register your models for translation.
We made a more complex example on how to register models [here](https://github.com/infoportugal/wagtail-modeltranslation-demo), please feel free to check it out.

Cheers

**Comment by dinosaxon** [comment]
Thank you @DiogoMarques29!

It seems that I have other issues now... May I ask you if it is possible to export the text so that I can translate it outside the CMS and import the translated back to the database? Any export format would be nice.

Thank you for your time.

**Comment by DiogoMarques29** [comment]
@dinosaxon this package does not offer a simple way of doing that. 
It might be of your interest the django dumpdata (https://docs.djangoproject.com/en/2.1/ref/django-admin/#dumpdata) and loaddata (https://docs.djangoproject.com/en/2.1/ref/django-admin/#loaddata).

Cheers
