### ISSUE TITLE
actually releasing 0.10b1 

### ISSUE THREAD

**Issue by Pomax** [infoportugal/wagtail-modeltranslation#231]
Django has been on 2.x for a long time now, Wagtail killed off 1.x support a while ago too, would it be possible to please release 0.10b1 as a real version v0.10, based on v0.13 of django-modeltranslation? 

I don't see anything that suggests there's a reason to hold up just releasing this, but in the mean time it's blocking people from upgrading to the versions of django and wagtail they _really_ should be on by now.

**Comment by Pomax** [comment]
Especially as people can't just add `wagtail-modeltranslation=="0.10b1"` to their pipfile: CI/CD will _not_ install this version unless "allow pre-release version for every single package, lol, good luck" is turned on. Which would be an incredibly bad idea of course.

**Comment by DiogoMarques29** [comment]
Hi @Pomax 
Just released v0.10

Cheers

**Comment by Pomax** [comment]
fantastic, thank you so much!
