### ISSUE TITLE
Default language duplication

### ISSUE THREAD

**Issue by abusquets** [infoportugal/wagtail-modeltranslation#232]
Hi,

with this settings

LANGUAGE_CODE = 'ca'

LANGUAGES = (
    ('ca', _('Catalan')),
    ('es', _('Spanish')),
    ('en', _('English')),
)

wagtail-modeltranslation creates the field 'title_ca', it a bug or it's normal?
Is there a way to avoid this behavior?

In this picture
https://github.com/infoportugal/wagtail-modeltranslation/blob/master/screenshot.png?raw=true
doesn't happen

For more information I use wagtail 2.4

Thanks

**Comment by DiogoMarques29** [comment]
Hi @abusquets 
It's normal. Wagtail modeltranslation uses django-modeltranslation to patch the models with the translation fields. It replicates the normal field, `title`, for all languages registered in your project, `title_ca`, `title_es` and `title_en`.
Currently there is no way to change this behavior.
Cheers
