### ISSUE TITLE
Running ./manage.py migrate/makemigrations/check yields "Unknown fields..."

### ISSUE THREAD

**Issue by tombreit** [infoportugal/wagtail-modeltranslation#233]
I'm trying to extend an existing wagtail project with wagtail-modeltranslation, but I'm not able get past adding ``wagtail_modeltranslation`` to my project.

**Problem**
Even after only adding 
``` python 
INSTALLED_APPS = [
    'wagtail_modeltranslation',
    'wagtail_modeltranslation.makemigrations',
    'wagtail_modeltranslation.migrate',
    ...my apps...
    ...wagtail apps...
]

LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French')),
)
```
to my project and trying to run ``makemigrations`` (or only ``check``), without any models registered for translation, django complains about   ``Unknown field(s)``:

``` bash
File ".../python3.7/site-packages/django/forms/models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (search_description_en, slug_en, search_description_fr, slug_fr, seo_title_fr, seo_title_en) specified for PublicationIndexPage
```

**Already tried**
* Tried with blank database: same result as above
* Tried without the legacy migration files: same result as above
* Removing ``wagtail.contrib.modeladmin`` from ``INSTALLED_APPS``: same result as above
* Tried registering some of my models: same result as above
* Tested https://github.com/infoportugal/wagtail-modeltranslation-demo, even with current dependencies (see below): works correctly

**Guess**
Could be related to https://github.com/infoportugal/wagtail-modeltranslation/issues/230#issuecomment-463653817 , as I do not have registered all pages for translation right now?

----
**Setup**
* Python 3.7
* Django 2.1.7
* Wagtail 2.4
* wagtail-modeltranslation 0.10
* django-modeltranslation  0.13

**Comment by tombreit** [comment]
Now I have registered *all* my page models, and this error is now gone. If that's (register all page-derived models for translation) a requirement to get wagtail-modeltranslation up and running, this could/should be mentioned in the docs.

**Comment by Akay7** [comment]
I'm getting the same error. 
The problem appears when page inherited from `AbstractEmailForm` was not registered in `modeltranslation`.

Is it necessary mention this in docs or change this behaviour?

**Comment by janbaykara** [comment]
I'm having the same issue. I notice the docs are very sparse and the imports in the code examples don't match those of other tutorials, like https://www.accordbox.com/blog/how-support-multi-language-wagtail-cms/.

**Comment by DiogoMarques29** [comment]
Hello!
In fact, registering all subclasses of page is a requirement. Please read point 2 of https://wagtail-modeltranslation.readthedocs.io/en/latest/Installation.html#quick-setup
If this is not clear, any ideia how we could document it?
Cheers
