### ISSUE TITLE
Editing interface does not expose translated fields for 'Orderable' class (wagtail.contrib.settings app)

### ISSUE THREAD

**Issue by tombreit** [infoportugal/wagtail-modeltranslation#236]
I have a ``wagtail.contrib.settings`` module with an ``Orderable`` class which should be translated via wagtail-modeltranslation (as my other page models) - but the editing interface for this class does not expose the translation fields.

**models.py**

``` python
# models.py
# ...imports
from wagtail.contrib.settings.models import BaseSetting, register_setting

@register_setting
class Topics(ClusterableModel, BaseSetting):
    panels = [
        InlinePanel(
            'topics',
            label='Topics',
        ),
    ]

class Topic(Orderable):
    topics = ParentalKey(
        Topics,
        related_name='topics',
    )
    name = models.CharField(
        max_length=255,
    )
    aliases = models.TextField(
        'Also known as',
        max_length=255,
        blank=True,
        help_text='What else is this known as or referred to as?',
    )

    panels = [
        FieldPanel('name'),
        FieldPanel('aliases'),
```

**translations.py**
``` python
from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register
from .models import Topic

@register(Topic)
class TopicTR(TranslationOptions):
    fields = ('name', 'aliases')
```

``makemigrations`` created the expected translation fields and the corresponding table in the database reflect these:

``` 
Migrations for 'core':
  core/migrations/0015_auto_20190318_2244.py
    - Add field aliases_en to topic
    - Add field aliases_fr to topic
    - Add field name_en to topic
    - Add field name_fr to topic
```

But the wagtail editing interface for this model does not expose these fields, instead just displays the "normal" wagtail editing interface. 

What am I missing?

----
**Setup**

*  Python  3.7
* Django 2.1.7
* Wagtail 2.4
* wagtail-modeltranslation 0.10
* django-modeltranslation 0.13

**Comment by DiogoMarques29** [comment]
Hello @tombreit 
You have to register `Topics` class in order to have inlines with translations.
```
@register(Topics)
class TopicsTR(TranslationOptions):
    pass
```
Because `Topics` is not registered for translation, all it's panels (in this case one `InlinePanel`) is not patched in the admin interface.
Cheers

**Comment by tombreit** [comment]
Dear @DiogoMarques29 , 
thank you very much for your support.
