### ISSUE TITLE
How to define different languages per site?

### ISSUE THREAD

**Issue by tombreit** [infoportugal/wagtail-modeltranslation#237]
In a wagtail multi-site setup, I would like to define the languages per site, or - better - make this configurable per site (via [SiteSettings](https://docs.wagtail.io/en/latest/reference/contrib/settings.html)) - is that possible? Any hints how to implement this?

**Comment by DiogoMarques29** [comment]
Hi @tombreit 
This feature is not in our plans, but feel free to give it a try!
Cheers
