### ISSUE TITLE
[CleandUP] Untranslated additional field in django-admin

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#24]
Refers the other issue i prefer open a new issue for this topic.
![borratodo](https://cloud.githubusercontent.com/assets/5034215/9284548/548e8d46-42a2-11e5-81d7-44a6207903bc.png)

See, create three addtional fields, but doesn't delete the initial field that now will be useless.

**Comment by rmartins90** [comment]
@SalahAdDin the purpose of this project is to use it with Wagtail CMS admin panel. We removed the logic part related to django-admin but we'll include it in next release. Thanks

**Comment by SalahAdDin** [comment]
Man, i doesn't mean that there is a problem with django-admin, i mean you can see the problem with django-admin, i think that won't be an additional field for the original untranslated field, i think that it's a spare field.

**Comment by dwasyl** [comment]
@rmartins90 Are you still planning to read the django-admin logic from modeltranslations? I have a need to use the django-admin interface for some of my site administration, and some through django-admin. I've been trying to figure out how to have both modeltranslations and wagtail-modeltranslations installed - but it does not seem to work very well (and is a bit redundant).

Any idea when it will be released? The current 0.5a1 doesn't seem to include the admin logic.

**Comment by Alexandre27** [comment]
In version 0.6 django-modeltranslation is a dependency so all their features should work without problems. BTW, @SalahAdDin in django-modeltranslation the original panel is not deleted, we did remove it but we had to make the default language required for fields which were originally required (django-modeltranslation makes all translations optional by default).
