### ISSUE TITLE
Makemigrations yields AttributeError, but only for initial makemigrations with custom AUTH_USER_MODEL

### ISSUE THREAD

**Issue by tombreit** [infoportugal/wagtail-modeltranslation#240]
On a new wagtail project, without any migration files and data yet, running the initial ``makemigrations`` fails when the wagtail_modeltranslation apps are referenced in ``INSTALLED_APPS``:

```python
INSTALLED_APPS = [
    'wagtail_modeltranslation',
    'wagtail_modeltranslation.makemigrations',
    'wagtail_modeltranslation.migrate',
    ...custom apps....
```

when using a custom user model via ``AUTH_USER_MODEL = 'users.CustomUser'`` with the following AttributeError: 

```bash
./manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/.../.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/.../.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/.../.venv/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/.../.venv/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/.../.venv/lib/python3.7/site-packages/wagtail_modeltranslation/management/commands/makemigrations_translation.py", line 27, in handle
    super(Command, self).handle(*args, **options)
  File "/.../.venv/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/.../.venv/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 170, in handle
    migration_name=self.migration_name,
  File "/.../.venv/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 44, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/.../.venv/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 184, in _detect_changes
    self.generate_altered_fields()
  File "/.../.venv/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 899, in generate_altered_fields
    new_field.remote_field.model._meta.app_label,
AttributeError: 'SettingsReference' object has no attribute '_meta'
```
I can not figure out what *that* error wants to tell me....

# Notice one
Commenting out the mentioned ``wagtail_modeltranslation*`` apps in ``INSTALLED_APPS`` and running ``makemigrations`` again does not yield any error and the initial migration files get created. 

Even if I now enable the ``wagtail_modeltranslation*`` apps in ``INSTALLED_APPS`` again and ran ``makemigrations`` a second time, it does not yield any error and the migration files for the translatable models get created. 

# Notice two
Commenting out the custom user model and running the initial ``makemigrations`` does *not* yield the mentioned AttributeError. 

----
Setup: 
* Django                   2.1.7   
* django-modeltranslation  0.13    
* wagtail                  2.4     
* wagtail-modeltranslation 0.10.1

**Comment by DiogoMarques29** [comment]
Hi @tombreit 
Can you show the definition of 'SettingsReference' class?

**Comment by tombreit** [comment]
That's weird - there is no ``SettingsReference`` in my code;-)

The only occurrence of  ``SettingsReference`` in the whole virtual environment for this project could be found in Django itself:
https://github.com/django/django/search?q=SettingsReference&unscoped_q=SettingsReference

**Comment by tombreit** [comment]
The same error also occurs after upgrading to 

Django==2.2
wagtail==2.5rc1

... were the ``SettingsReference`` class war removed from Django (in Django 2.2): 

https://github.com/django/django/blob/stable/2.2.x/django/db/migrations/writer.py

**Comment by tombreit** [comment]
Dear @DiogoMarques29 , I've set up a "blank", minimal wagtail + wagtail-modeltranslation + custom user demo project in which this error could be replicated:

https://gitlab.com/tombreit/wagtail-modeltranslation-customuser

1. Installed wagtail
1. Created blank demo project: ``wagtail start demo``
1. Added custom user: https://docs.wagtail.io/en/v2.4/advanced_topics/customisation/custom_user_models.html
1. Added wagtail-modeltranslation: https://github.com/infoportugal/wagtail-modeltranslation
1. ``./manage.py makemigrations`` -> ``AttributeError: 'SettingsReference' object has no attribute '_meta'``

Thanks for your support

**Comment by DiogoMarques29** [comment]
Thanks @tombreit 
Going to check that out.

**Comment by DiogoMarques29** [comment]
Hi @tombreit 
If you run `./manage.py makemigrations_original` and then `./manage.py makemigrations` it will work.
Still don't know why the first makemigrations fails on your project, but you have this work arround!
Cheers

**Comment by tombreit** [comment]
Ok, but if I run ``./manage.py makemigrations_original`` (which, as you noted,  does not throw any errors), it creates a new migration file for ``ẁagtail/core``. That would clash on the next upgrade of wagtail: 

```bash
$ ./manage.py makemigrations_original
Migrations for 'wagtailcore':
  .venv/lib/python3.7/site-packages/wagtail/core/migrations/0042_auto_20190411_2236.py
    - Add field search_description_es to page
    - Add field search_description_fr to page
    - Add field search_description_pt to page
    - Add field seo_title_es to page
    - Add field seo_title_fr to page
    - Add field seo_title_pt to page
    - Add field slug_es to page
    - Add field slug_fr to page
    - Add field slug_pt to page
    - Add field title_es to page
    - Add field title_fr to page
    - Add field title_pt to page
    - Add field url_path_es to page
    - Add field url_path_fr to page
    - Add field url_path_pt to page
Migrations for 'home':
  home/migrations/0001_initial.py
    - Create model HomePage
Migrations for 'users':
  users/migrations/0001_initial.py
    - Create model CustomUser
```

Another possible workaround (without adding upstream migration files): 

1. initial project with custom user class without any migration files
1. comment out ``wagtail_modeltranslation*`` in ``INSTALLED_APPS``
1. ``./manage.py makemigrations``
1. comment in ``wagtail_modeltranslation*`` in ``INSTALLED_APPS``
1. ``./manage.py makemigrations``
1. ``./manage.py migrate`` (translation db schema updates will run on this step)

**Comment by DiogoMarques29** [comment]
My mistake @tombreit 
It does indeed create a migration in wagtail core, which it wasn't suppose to. I'll try to investigate the real problem today.

**Comment by DiogoMarques29** [comment]
A bit more info @tombreit 
What we are doing [here](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/management/commands/makemigrations_translation.py#L7) is to ensure that no changes are detected in wagtailcore page model. When a project defines a new user model, that changes the way owner field of model page changes, so there are 2 changes to page model:
1. add new fields for translated languages (the change we don't want makemigrations to detect)
2. owner field now points to a `SettingsReference` (this change we need to let makemigrations detect)

So, a work arround could be:
1. Setup the project like you did...
2. Comment out:
```
    #'wagtail_modeltranslation',
    #'wagtail_modeltranslation.makemigrations',
    #'wagtail_modeltranslation.migrate',
```
3. Run `makemigrations` (only the owner field change is detected)
4. Comment in:
```
    'wagtail_modeltranslation',
    'wagtail_modeltranslation.makemigrations',
    'wagtail_modeltranslation.migrate',
```
5. Run `makemigrations` again (this time, it's our makemigrations that will run, so we ensure no changes are detected on page model)

**Comment by tombreit** [comment]
Dear @DiogoMarques29 , thanks for your explanation. So I will stay with  the workaround I mentioned in https://github.com/infoportugal/wagtail-modeltranslation/issues/240#issuecomment-482357792 and you verified in https://github.com/infoportugal/wagtail-modeltranslation/issues/240#issuecomment-482581623

I'm quite new to (django|wagtail)-modeltranslation and I am surprised that I could not find others running in this wagtail-custom-user-error. Perhaps a hint in the docs would be nice, in the [Caveats](https://wagtail-modeltranslation.readthedocs.io/en/latest/caveats.html) section? I don't feel comfortable with *-modeltranslation enough yet to write a nice merge request here...
