### ISSUE TITLE
Javascript error: Cannot read property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by Ramblurr** [infoportugal/wagtail-modeltranslation#243]
```
jquery-3.2.1.min.js:2 Uncaught TypeError: Cannot read property 'innerHTML' of undefined
    at HTMLDocument.<anonymous> (copy_stream_fields.js:20)
    at j (jquery-3.2.1.min.js:2)
    at k (jquery-3.2.1.min.js:2)
(anonymous) @ copy_stream_fields.js:20
j @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
```

[the line in question](https://github.com/infoportugal/wagtail-modeltranslation/blob/8deb0424f1bce69e9066027edd45c74126d6917e/wagtail_modeltranslation/static/wagtail_modeltranslation/js/copy_stream_fields.js#L20)

This error occurs when editing a page that is a StreamField. This breaks the copy content button.

**Comment by DiogoMarques29** [comment]
Hi @Ramblurr 
What version of django, wagtail and wagtail-modeltranslation are you using?

Cheers

**Comment by Ramblurr** [comment]
django 2.2.1
wagtail 2.5.1
wagtail-modeltranslation 0.10.1

The error isn't happening on all pages, just one. The source is available here: 

https://gitlab.com/streetnoiseorchestra/streetnoise.at/blob/master/home/models.py in the `HomePage` class (line 74)

**Comment by DiogoMarques29** [comment]
Hi @Ramblurr 
Can you confirm commit 92889054aaf1c3820b0833b69208044a4326a7b9 fixes this?
Cheers
