### ISSUE TITLE
wagtail_modeltranslation.makemigrations creates new but identical migration files for a custom user

### ISSUE THREAD

**Issue by tombreit** [infoportugal/wagtail-modeltranslation#244]
On a project with a custom user model, ``wagtail_modeltranslation.makemigrations`` creates a new migration file each time I call ``makemigrations``, even if the codebase was not touched. These migration files are identical (except the dependency) and do always alter the model manager: 

```pyhton
    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
```

# Steps to reproduce
## For a minimal, clean environment
1. Demo project: https://gitlab.com/tombreit/wagtail-modeltranslation-customuser
1. ``pip install -r requirements.txt``
1. comment out wagtail_modeltranslation* in INSTALLED_APPS
1. ``./manage.py makemigrations``
1. comment in wagtail_modeltranslation* in INSTALLED_APPS
1. ``./manage.py makemigrations``
1. ``./manage.py migrate``

## Replicate this issue
8. ``./manage.py makemigrations`` creates ``users/migrations/0002_auto_20190503_1517.py``:

```python
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
```
9. do not touch/modify the codebase, just run ``./manage.py makemigrations`` a second (third, fourth) time and an identical, additional migration file gets created ``users/migrations/0003_auto_20190503_1517.py``

```python
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190503_1517'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
```

**Comment by DiogoMarques29** [comment]
Hi @tombreit 
Any reason for you to register CustomUser for translation?

**Comment by tombreit** [comment]
Dear @DiogoMarques29 , 
you're absolutely right: I do not know why I registered the CustomUser model for translation, as I do not have any translatable fields for this CustomUser right now. After removing the TranslationOptions for this CustomUser, no more redundant migration files get created for this model.
