### ISSUE TITLE
Content from default language is saved to language the request is in.

### ISSUE THREAD

**Issue by Hopiu** [infoportugal/wagtail-modeltranslation#247]
When I create or edit a page in the wagtail admin, content from fields of the default language get saved to the language the current request is in, when these fields are empty.

For example, when I create a new page, let's say in English, when my browser is set to French. I only enter English content and leave the French fields empty. Then I publish the page. Now the content of the English fields are also saved to the French fields.

I don't know, maybe it has something to do with what I found in the modeltranslation docs:

> By default modeltranslation will use the current request language for prepopulating admin fields specified in the prepopulated_fields admin property. This is often used to automatically fill slug fields.

I couldn't find a way around it. Has someone an idea where that could happen? Pages created from the shell are not affected.

The modeltranslation setting `MODELTRANSLATION_AUTO_POPULATE = False` doesn't help either.

**Comment by buczek** [comment]
I think, that is deschler/django-modeltranslation#382
