### ISSUE TITLE
rendering the current locale in a template?

### ISSUE THREAD

**Issue by Pomax** [infoportugal/wagtail-modeltranslation#249]
It doesn't look like there's a way to template the current locale into a template - I had a look at the template tags file but I don't see anything that lets me say something like:

```
{% load wagtailmetadata_tags %}
{% get_current_locale as locale %}
<meta name="og:locale" content="{{ locale }}">
```

Is there a way to already do this? If not, I suppose this is a feature request? =P

**Comment by lohmander** [comment]
Is `request.LANGUAGE_CODE` what you're looking for?

**Comment by Pomax** [comment]
I was hoping there was a clean templating var, rather than having to reach into Django

**Comment by lohmander** [comment]
How about

```
{% load i18n %}

{% get_current_language as locale %}
```

I believe it's pretty much what you were describing? :)

**Comment by Pomax** [comment]
fun fact: I've had that take down production because it got included on a 404 page that was served outside of the i18n patterns, so... no, I'd much rather have a tag that actually works and returns a safe value even if it's run outside of i18n context =D

**Comment by DiogoMarques29** [comment]
@Pomax 
I agree with @lohmander 
https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#get-current-language
