### ISSUE TITLE
Change language in page preview's issue in preview

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#25]
Create a seperate thread for this bug.

![language_chooser_problem](https://cloud.githubusercontent.com/assets/5034215/9297169/5c4afdfc-4460-11e5-9d3e-80c3d3e32085.png)
Try to change the language through language chooser in a page's preview.

**Comment by rmartins90** [comment]
Can't reproduce this error, please try with latest version
