### ISSUE TITLE
Unable to translate slugs for a link

### ISSUE THREAD

**Issue by sukhada** [infoportugal/wagtail-modeltranslation#250]
I'm trying to implement a language switcher, for which I'm using the Django recommended form:
```
    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
        {% get_current_language as LANGUAGE_CODE %}
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <input name="language" type="hidden" value="{% if LANGUAGE_CODE == 'en' %}es{% else %}en{% endif %}">
    </form>
```
My urls.py is set up like so:
```
urlpatterns = [

    # Wagtail urls
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),

    # Django urls
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),

]

urlpatterns += i18n_patterns(
    path(r'', include(wagtail_urls))
)
```

When I click to change my language, I am correctly forwarded to /en/slug or es/slug, depending on the language I have selected. However the actual slug value is not being translated. Since I have Spanish slugs for the Spanish pages, I am getting a 404 when I switch languages, because I am directed to the English slug value paired with the Spanish locale prefix (es).

I also tried using the `slugurl_trans` template tag, but that didn't seem to work (maybe because I'm not explicitly defining any URLs in my `i18n_patterns` call?).

Any guidance on this would be really helpful, as I've spent way too many hours on this!

**Comment by DiogoMarques29** [comment]
Hi @sukhada 
try using templatetag 'change_lang'.
```
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% get_active_languages as languages %}
    {% for lang in languages %}
        {% if lang != LANGUAGE_CODE %}<a class="dropdown-item" href="{% change_lang lang %}">{{ lang }}</a>{% endif %}
    {% endfor %}
</div>
```
