### ISSUE TITLE
ImportError: cannot import name 'CopyForm' from 'wagtail.admin.forms'

### ISSUE THREAD

**Issue by robnardo** [infoportugal/wagtail-modeltranslation#254]
## Problem
When trying to add wagtail-modeltranslation, I get the following error:
```
ImportError: cannot import name 'CopyForm' from 'wagtail.admin.forms'
```

## Solution
Did some debugging and found a possible solution.  It seems all I need to do is change line 12 in wagtail_modeltranslation/patch_wagtailadmin_forms.py to

```
from wagtail.admin.forms.pages import CopyForm
```

## My Setup
I am using Python 3.7 with the following packages:

/code # pip freeze
beautifulsoup4==4.6.0
certifi==2019.6.16
chardet==3.0.4
dj-database-url==0.5.0
Django==2.2.5
django-appconf==1.0.3
django-cache-url==3.0.0
django-cogwheels==0.2
django-colorful==1.3
django-compressor==2.2
django-dotenv==1.4.2
django-el-pagination==3.2.4
django-modelcluster==4.4
django-modeltranslation==0.13.3
django-redis==4.10.0
django-social-share==1.3.2
django-taggit==0.24.0
django-treebeard==4.3
djangorestframework==3.10.3
draftjs-exporter==2.1.6
html5lib==1.0.1
idna==2.8
lxml==4.4.1
Pillow==6.1.0
puput==1.0.5
pytz==2019.2
rcssmin==1.0.6
redis==3.3.8
requests==2.22.0
rjsmin==1.0.12
six==1.12.0
sqlparse==0.3.0
Unidecode==1.1.1
urllib3==1.25.3
uWSGI==2.0.17
wagtail==2.6.1
wagtail-modeltranslation==0.10.3
wagtailmenus==2.13.1
webencodings==0.5.1
Willow==1.1

**Comment by DiogoMarques29** [comment]
Hi @robnardo 
Correct, PR #253 fixes this, going to merge and release a new version.
Cheers
