### ISSUE TITLE
Deprecation of EditHandler.bind_to_model(model)

### ISSUE THREAD

**Issue by jorenham** [infoportugal/wagtail-modeltranslation#255]
It will be removed in Wagtail 2.7
https://github.com/infoportugal/wagtail-modeltranslation/blob/f52993d73c98cd4d162565489fade566119b1e3a/wagtail_modeltranslation/patch_wagtailadmin.py#L144

**Comment by easherma** [comment]
I opened a PR for this here: 
https://github.com/infoportugal/wagtail-modeltranslation/pull/257

However, it looks like it may be a breaking change for some significantly older versions of Wagtail.

**Comment by DiogoMarques29** [comment]
Fixed in #258

**Comment by easherma** [comment]
@DiogoMarques29 thanks for the merge! could we push out a new version with these latest changes? We are using this as a dependency in a docker container that dosen't have Git at the moment, so it would be nice to have a new release for PyPi

**Comment by DiogoMarques29** [comment]
Just released new version: v0.10.6 @easherma 

Cheers
