### ISSUE TITLE
[CleandUP] [Optionally]Promote panels ordering

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#26]
Do not misunderstand me friend, I really find it a very useful alternative multilanguage Wagtail, django-cms uses the same type of fields to multi-language pages, and the same is to get reports, to help and ideas.

I think about promote panels that should be more tidy and elegant:
![promote panels tr](https://cloud.githubusercontent.com/assets/5034215/9297708/38800a6c-4469-11e5-8383-f010c41d9d99.png)

As you can see in the picture, all the fields appear one after the other, and it looks pretty bad, I think it best to put the fields in each language in separate panels and the end panel of the image is separated, thisIt gives more order and stilo page.

![promote panels fin](https://cloud.githubusercontent.com/assets/5034215/9297764/f3ae2896-4469-11e5-98ab-4b8ba91bdeb4.png)

**Comment by Alexandre27** [comment]
We will not do that as it involves looking for specific fields in specific panels. But you can achieve this by defining the promote_panels (like you define content_panels) and create multifieldpanels for the fields you want to group.
eg:
promote_panels = [
        MultiFieldPanel("slug"),
        MultiFieldPanel("seo_title"),
    ]

**Comment by SalahAdDin** [comment]
Yes, but how can we make groups for specific language fields.

**Comment by SalahAdDin** [comment]
Yes, but how can we make groups for specific language fields?

**Comment by Alexandre27** [comment]
@SalahAdDin You can't. As we try to keep it simple and you only have to define the panels for the original fields, you can't create groups to organize languages.

**Comment by SalahAdDin** [comment]
@Alexandre27 , it is a big problem, because is not comfortable and ordered.
