### ISSUE TITLE
Add setting to disable language_toggles / locale-picker

### ISSUE THREAD

**Issue by urlsangel** [infoportugal/wagtail-modeltranslation#262]
The new `locale-picker`in `0.10.7` is great for snippets, but it breaks our model of separating out locales to tabs in page editors.

Could you add a settings flag to disable insertion of this JS for page editing? 

I've hidden the added `locale-picker` DOM element with inserted CSS, but the JS still toggles the visibility of the unselected locale fields, rendering the content in those tabs blank.

**Comment by DiogoMarques29** [comment]
Hi @urlsangel 
The JS is injected [here](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/wagtail_hooks.py#L70), but i don't think we can distinguish between a request for snippet edit or a page edit.
Any ideas on how to implement this?

**Comment by urlsangel** [comment]
Hi @DiogoMarques29 

If you can't tell by the request, then you could return out of the injected JS itself by adding a test for where you are at the top of the script:

```
if (!$('body#wagtail.page-editor').length) {
    return;
}
```

Thanks for getting back to me so quickly :-)

Russell.

**Comment by DiogoMarques29** [comment]
A new setting was added here 408d99f0f8bf6b4d7b360d7f682c471bebcb0e09 and v0.10.10
Set `WAGTAILMODELTRANSLATION_LOCALE_PICKER = False` to globally disable the locale-picker.
