### ISSUE TITLE
404 Error raised when using the `change_lang` template tag in preview

### ISSUE THREAD

**Issue by simonbru** [infoportugal/wagtail-modeltranslation#263]
Previewing an _unpublished_ page results in a 404 error when the template uses the `change_lang` template tag. This is caused by the following line raising an `Http404` exception that is not caught:
https://github.com/infoportugal/wagtail-modeltranslation/blob/28b304aa487ca89ff65f4cbb6e1bde0b062695f8/wagtail_modeltranslation/templatetags/wagtail_modeltranslation.py#L45

**Comment by DiogoMarques29** [comment]
Hi @simonbru 
This was fixed in last version 0.10.8

**Comment by simonbru** [comment]
Great ! Thanks
