### ISSUE TITLE
Add setting to disable automatic Page translations

### ISSUE THREAD

**Issue by rvdrijst** [infoportugal/wagtail-modeltranslation#268]
I'm using `wagtailtrans` for the translation of the page tree.

I still want to use `wagtail-modeltranslation` for settings and snippets. However, when I add `wagtail_modeltranslation` to the `INSTALLED_APPS` I immediately get the following error:

```django.core.exceptions.FieldError: Unknown field(s) (title_en, slug_nl, search_description_en, slug_en, title_nl, search_description_nl, seo_title_nl, seo_title_en) specified for TranslatablePage```

This is because internally, `wagtail-modeltranslation` is registring `TranslationOptions` for the `Page` model, something I don't want.

My workaround right now is to use the (undocumented) setting:
```python
MODELTRANSLATION_ENABLE_REGISTRATIONS = False
```

This disables _all_ automatic registration, so I have added an `apps.py` with the following content to every app I have a `translation.py` for:

```python
from django.apps import AppConfig

class DefaultAppConfig(AppConfig):
    name = 'my_app'
    verbose_name = "My App"

    def ready(self):
        from .translation import MyModelTR
        from wagtail_modeltranslation.patch_wagtailadmin import patch_wagtail_models
        patch_wagtail_models()
```

This is the `DefaultAppConfig` I put in the `INSTALLED_APPS` in settings.

This works for me but it could get cumbersome if you have a lot of apps that have translations.
It would be nice if there was a setting like 
```python
MODELTRANSLATION_DISABLE_PAGE_TRANSLATIONS = True
```
 or something similar that simply doesn't load the translation options for `Page`.

**Comment by DiogoMarques29** [comment]
I believe this could be accomplished by adding a validation [here](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/patch_wagtailadmin.py#L67).
PR are welcome! :)

**Comment by rvdrijst** [comment]
Unfortunately I don't have the time at the moment to prepare a pull request, but I did find another issue, just posting a quick hack here for other people that might run into this.

Problem: copying pages doesn't work if you install `wagtail-modeltranslation` but don't want page translations.

Quick hack: add this in the `ready` method of one of your `AppConfig`s:
```python
# bit of a hack to unhook the modeltranslation hook
from wagtail.core import hooks
# make sure hooks are loaded
hooks.search_for_hooks()
from wagtail_modeltranslation.wagtail_hooks import before_copy_page, register_localized_page_link_handler
hooks._hooks['before_copy_page'].remove((before_copy_page, 0))
# may not be a problem but not needed, so remove
hooks._hooks['register_rich_text_link_handler'].remove((register_localized_page_link_handler, 0))
```
In `wagtail-modeltranslation` this can be fixed by only registring these when the `Page` model is translated (similar to the `LOCALE_PICKER` setting).

**Comment by DiogoMarques29** [comment]
Consider using `django-modeltranslation` and patch the snippet forms in your code.
