### ISSUE TITLE
sdist releases are missing on pypi

### ISSUE THREAD

**Issue by DavHau** [infoportugal/wagtail-modeltranslation#269]
While pinning `wagtail-translation==1.10.*` I got the error from pip:

ERROR: Could not find a version that satisfies the requirement wagtail-modeltranslation==0.10.* (from -r /tmp/tmp__f6o6mq/74fa0476b372e869ac7eaec824d65d5f.txt (line 9)) (from versions: 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0a0, 0.5.0a1, 0.6.0rc1, 0.6.0rc2, 0.8a1, 0.8, 0.8.1, 0.9.0)

It seems like from verison 1.10.x on there are only wheel distributions available on pypi.

See for example version 0.9.0 (sdist file available):
https://pypi.org/project/wagtail-modeltranslation/0.9.0/#files
vs. version 0.10.10 (no sdist file):
https://pypi.org/project/wagtail-modeltranslation/0.10.10/#files

Not all platforms / installation tools support wheels.
Could you please push sdist releases again in the future?

**Comment by DiogoMarques29** [comment]
Future releases will have sdist.
A new release was uploaded with sdits (0.10.12).
Thanks
