### ISSUE TITLE
Locale Picker ignores zh-hans and zh-hant locales

### ISSUE THREAD

**Issue by fefeme** [infoportugal/wagtail-modeltranslation#275]
## Issue Summary

The locale picker ignores language codes zh-hant and zh-hans.

## Steps to reproduce
Add zh-hans and zh-hant to the LANGUAGES settings.

```LANGUAGES = [
    ('en', _('English')),
    ('zh-hans', _('Simplified Chinese')),
    ('zh-hant', _('Traditional Chinese'))
]
```
They are missing in the locale picker.

I tracked this down to the regex in language_toggles.js / filterForLocale skipping language codes that don't match the form ww-ww.

**Comment by DiogoMarques29** [comment]
Fixed in #276
