### ISSUE TITLE
FroalaField is not supported by modeltranslation

### ISSUE THREAD

**Issue by KamilRAliyev** [infoportugal/wagtail-modeltranslation#278]
Dear team, I am using **frola** editor on my **django** project. Today I tried to write modeltranslations for my website. it throws error :
`django.core.exceptions.ImproperlyConfigured: FroalaField is not supported by modeltranslation.`
on command
`python manage.py makemigrations`

Is there solution for this problem?

**Comment by DiogoMarques29** [comment]
Hi @KamilRAliyev 
You have to add `MODELTRANSLATION_CUSTOM_FIELDS = ('FroalaField',)` to your settings.
I'll do an update to the documentation asap to reflect this.
Cheers

**Comment by DiogoMarques29** [comment]
Sorry, this is a setting for `django-modeltranslation`.
[Here](https://wagtail-modeltranslation.readthedocs.io/en/latest/advanced%20settings.html#advanced-settings) you have a link to all settings provided by `django-modeltranslation`.
