### ISSUE TITLE
Can not update content in StreamField

### ISSUE THREAD

**Issue by suxilog** [infoportugal/wagtail-modeltranslation#280]
I am adding i18n to a exist website build with StreamField,   but update_translation_fields command not work with StreamField.  All field can be updated except content in StreamField. Already follow this https://github.com/infoportugal/wagtail-modeltranslation/issues/186#issuecomment-375268868 ,but not work for me.

Is this a bug or my missing step?

Will it be possible to update wagtail-modeltranslation-demo with StreamField example? I think streadfield translation of wagtail will be explained more clearly.

Version: 
wagtail 2.8, 
django 2.2,
wagtail_modeltranslation==0.10.13

**Comment by DiogoMarques29** [comment]
Hello @suxilog 

I updated wagtail-modeltranslation-demo with this issue.
Steps to reproduce:

create virtualenv

pip install -r requirements.txt

./manage.py migrate

./manage.py createsuperuser

./manage.py runserver

Create a homepage and populate streamfield

Uncomment `fields = ('st',)` in translations.py

./manage.py makemigrations && ./manage.py migrate

./manage.py runserver

Confirm the stream field has `pt` (the default language) value is populated.

Cheers

**Comment by suxilog** [comment]
Thanks for reply. 
I do some test yesterday. There is no problem for  new app to use update streamfield.  the problem only come out when update a exist stream field. 
For example: 
blog model have a content stream field. Already have 3 record. When use sync_page_translation_fields . it can create content_en and content_zh_hans . I set zh_hans as default language. but when use update_translation_fields,  the content_zh_hans field can not update. Still Null.  I dont know why. Just let you know. 
Thanks again.

**Comment by DiogoMarques29** [comment]
I forgot to mention the update_translation_fields after the makemigrations && migrate.
In my example, it woks.

**Comment by suxilog** [comment]
It works, thanks.
