### ISSUE TITLE
Toggle all languages on default editing

### ISSUE THREAD

**Issue by birkoss** [infoportugal/wagtail-modeltranslation#287]
Hi,

I'm trying to enable editing on all languages by default, like this : https://www.screencast.com/t/hNOKRyIuF30J

I was able, when manually editing language_toggles.js : https://www.screencast.com/t/wRedUnAbF

Is there any other (clean) way to achieve this ?

Thanks,

**Comment by DiogoMarques29** [comment]
Hello @birkoss 
You can disable language toggle via settings, but that removes the toggle buttons.
Another approach is to write your own JS and use a hook to inject the JS into the page editor like we do here: https://github.com/infoportugal/wagtail-modeltranslation/blob/e2b26fefcecb85546fe65a143607406e0b26b274/wagtail_modeltranslation/wagtail_hooks.py#L71-L93

Cheers

**Comment by buczek** [comment]
> You can disable language toggle via settings, but that removes the toggle buttons.

How?

It would be nice, if you could keep the toggle buttons and have them all (or a specific set) activated by default, not just a single language (LANGUAGE_CODE).

Side note: With
```
LANGUAGE_CODE = 'en-us'
LANGUAGES = (
    ('en', _('English')),
    ('de', _('German')),
)
```
even 'en' is not activated by default. In an existing system, you can't just update LANGUAGES. And 'en-us' seems to be a valid setting for LANGUAGE_CODE.

**Comment by DiogoMarques29** [comment]
https://wagtail-modeltranslation.readthedocs.io/en/latest/advanced%20settings.html#wagtailmodeltranslation-locale-picker

'en' is not activated because the default language does not match 'en'. We could do some parsing to try and match those, but must be aware that some projects might have 'en-us' and 'en-gb' for example.
PR are welcome!

Cheers

**Comment by buczek** [comment]
> https://wagtail-modeltranslation.readthedocs.io/en/latest/advanced%20settings.html#wagtailmodeltranslation-locale-picker

Oops, don't know how I missed that.

**Comment by buczek** [comment]
@DiogoMarques29: Something like buczek/wagtail-modeltranslation#1 acceptable to address the initial request?
