### ISSUE TITLE
/api/v2/pages configuration

### ISSUE THREAD

**Issue by pierregm** [infoportugal/wagtail-modeltranslation#295]
Hello,
I'm working on a bilingual (en/fr) app (wagtail 2.10.1, wagtail-modeltranslation 0.10.14) and I'm trying to set up the `/api/v2/` endpoints.
At the moment, I can access the pages for only one language (en), eg 
```
# Example entry for /api/v2/pages/
{
            "id": 3,
            "meta": {
                "type": "home.HomePage",
                "detail_url": "http://localhost:8000/api/v2/pages/3/",
                "html_url": "http://localhost:8000/en/",
                "slug": "home",
                "first_published_at": null
            },
            "title": "Welcome"
        },
...
```
even if my settings are
```
LANGUAGES = (("fr", _("French")), ("en", _("English")))
MODELTRANSLATION_LANGUAGES = ("fr", "en")
MODELTRANSLATION_DEFAULT_LANGUAGE = "fr"
MODELTRANSLATION_PREPOPULATE_LANGUAGE = "fr"
```

* Is the `/api/v2` supported yet ?
* If so, are there any specific configuration steps I'd need to follow, and where could I find them ?

Thanks a lot in advance.

**Comment by DiogoMarques29** [comment]
Hi @pierregm 
I believe you need to activate the locale for the current request.
Check how django handles current language for request here: https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#how-django-discovers-language-preference

Cheers
