### ISSUE TITLE
Fields together in MultiFieldPanel -> FieldRowPanel

### ISSUE THREAD

**Issue by bplociennik** [infoportugal/wagtail-modeltranslation#296]
Is any possible to have fields like on the image without hardcoding them in the edit handler?

![image](https://user-images.githubusercontent.com/6594923/91859679-06ebe480-ec6b-11ea-8cf3-95a562caf752.png)

```
MultiFieldPanel(
            [
                FieldRowPanel(
                    [
                        TextareaFieldPanel("hero_title"),
                        TextareaFieldPanel("hero_title_ru"),
                    ]
                )
            ],
            heading="hero title",
            classname=["multi-field", "collapsible"]
        )
```

**Comment by DiogoMarques29** [comment]
Hello!
Have you tried to set only `TextareaFieldPanel("hero_title"),` inside `FieldRowPanel`?

**Comment by bplociennik** [comment]
@DiogoMarques29 yep is working without `FieldRowPanel` but unfortunately, I need this in that way :(

**Comment by bplociennik** [comment]
I think that it's something related with TextareaFieldPanel because with `FieldPanel` is working great inside MultiFieldPanel->FieldRowPanel.

![image](https://user-images.githubusercontent.com/6594923/91871493-88e20a80-ec77-11ea-95c0-d90ff099e67e.png)


```
MultiFieldPanel(
            [
                FieldRowPanel(
                    [FieldPanel("who_description")]
                )
            ],
            heading=_("who we are description"),
            classname="collapsible",
        ),
```

**Comment by bplociennik** [comment]
I figure out that my custom `TextareaFieldPanel` is not working because of https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/patch_wagtailadmin.py#L53 - so I only need to add this there and its works.

```
class TextareaFieldPanel(FieldPanel):
    widget = Textarea
```
