### ISSUE TITLE
Other idioms in new tab

### ISSUE THREAD

**Issue by chimeno** [infoportugal/wagtail-modeltranslation#3]
Hello,
It could be possible to have:
## CONTENT [EN] | CONTENT [ES] | CONTENT [FR]

Instead the actual:
Tittle [es]
Tittle [en]

I could help with that if any give me some direction.

**Comment by rmartins90** [comment]
Sure, it's possible. The problem are the inlinepanels.
In order to achieve that change you need to rethink the construction of the model form, you can find it on _patch* methods on models.py.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by SalahAdDin** [comment]
Here there are a tutorial: http://www.coactivate.org/projects/ejucovy/blog/2014/05/10/wagtail-notes-custom-tabs-per-page-type/

**Comment by rmartins90** [comment]
I'll release this feature soon, as well as fix for issues related to translating inline models.

**Comment by SalahAdDin** [comment]
@rmartins90 when?

**Comment by SalahAdDin** [comment]
@rmartins90 When we will have this feature?

**Comment by rmartins90** [comment]
Not soon, there's other issues that need fix first.

**Comment by SalahAdDin** [comment]
When?

**Comment by GaretJax** [comment]
👍

**Comment by DiogoMarques29** [comment]
closed in favour of #211
