### ISSUE TITLE
Populate Page fields while upgrading from versions before v0.8

### ISSUE THREAD

**Issue by hyperstown** [infoportugal/wagtail-modeltranslation#305]
Hi, I'm upgrading from version v0.6 to v0.10.13 and I cannot find a way to populate Page fields (title_xx, slug_xx, seo_title_xx). Command `python manage.py sync_page_translation_fields` only creates new fields in database but leaves them empty. Is there an easy way to retrieve information form old fields and push it to the new ones?
I also tried to run `python manage.py makemigrations_translation` but it only deletes old fields.

**Comment by DiogoMarques29** [comment]
Hello @hyperstown 
You should run: https://wagtail-modeltranslation.readthedocs.io/en/latest/management%20commands.html#the-update-translation-fields-command
Cheers
