### ISSUE TITLE
All translated fields hidden in wagtail admin on page load

### ISSUE THREAD

**Issue by olivierdalang** [infoportugal/wagtail-modeltranslation#309]
Hi,

In wagtail admin all translated fields are hidden on page load, until I click on one of the languages button.

I have the javascript error below, that originates from the default language not being properly populated.

Being the first in the list, `fr` should be my default language, but the wagtailModelTranslations javascript config shows `en-us`.

Thanks for the otherwise awesome extension.

(using wagtail 2.10 and wagtail-modeltranslation 0.10.13)

```python
# settings.py
LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
    ('ar', _('Arabic')),
]
```

```html
<!-- what appears in the source -->
<script>
wagtailModelTranslations = {
languages: ['fr', 'en', 'ar'],
defaultLanguage: 'en-us',
viewEditString: 'View / edit fields for',
translate_slugs: 'true',
};
</script>
```

```javascript
// javascript trace
jquery-3.5.1.min.js?v=241daae7:2 Uncaught TypeError: Cannot read property 'click' of undefined
    at HTMLDocument.<anonymous> (language_toggles.js:174)
    at e (jquery-3.5.1.min.js?v=241daae7:2)
    at t (jquery-3.5.1.min.js?v=241daae7:2)
```

**Comment by DiogoMarques29** [comment]
@olivierdalang 
I believe that problem was solved in 0.10.14
Re-open if the issue still happens.
Cheers
