### ISSUE TITLE
Internal server error when debug=False due to 404.html template

### ISSUE THREAD

**Issue by olivierdalang** [infoportugal/wagtail-modeltranslation#315]
Hi !

Just had a very confusing issue where setting debug=False would cause an exception because of the presence of a 404.html template (which I took from the wagtail template project).

Removing the file fixes the error.

It seems to happen when one requests a page without the language prefix. To me it's really not clear why this triggers the rendering of the 404 page ?! It's also not clear why the debug setting has an influence on this ?

The error is especially nasty as it doesn't output anything by default when run with gunicorn, making it hard to debug.

Here's the report that helped me fix the issue : https://stackoverflow.com/questions/63879245/wagtail-modeltranslation-doesnt-work-with-debug-false

**Comment by olivierdalang** [comment]
It looks like the culprit is the `{% change_lang language page %}` tag that I have in my base template (to display a dropdown menu to switch language in the site header). When page is None (which is the case on a 404 page), that tag throws an exception, which isn't displayed nowhere so extra annoying to debug.

**Comment by DiogoMarques29** [comment]
Hello @olivierdalang 
Thanks for the PR. Merged.

Cheers
