### ISSUE TITLE
offtopic: Transfer of wagtail-embedvideos ownership

### ISSUE THREAD

**Issue by bashu** [infoportugal/wagtail-modeltranslation#321]
Hi,

This repository infoportugal/wagtail-embedvideos seems to lack maintenance (I know it's archived), I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

PS: We still use it some legacy projects and I am willing to keep it maintained.

PPS: If you are not sure about me, for example I maintain (or helping):

PPPS: I've tried to reach you via https://infoportugal.pt, but contact form not working, nor replies from geral@infoportugal.pt

https://github.com/shanx/django-maintenancemode

https://github.com/adamcharnock/django-tz-detect

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps

**Comment by DiogoMarques29** [comment]
Hello @bashu 
Please contact me diogo.marques@infoportugal.pt

Cheers
