### ISSUE TITLE
Need an example language switcher in template 

### ISSUE THREAD

**Issue by agelinas** [infoportugal/wagtail-modeltranslation#33]
It would be good to add an example of a language switcher in the Documentation. It has been removed in README.1st and I'm sure it would be quite helpfull. I would need it myself.

I will add it in the Documentation ...

Thank you

Alain

**Comment by rmartins90** [comment]
Did you handle this agelinas?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by agelinas** [comment]
I

**Comment by agelinas** [comment]
There is a Language switching form example in the Django Docs which is okay but I don't like having  to click on the GO button to activate the language choice. There are some examples I found elsewhere that use javascript to do away with the need of a 'GO' button, but I was unable to get the code working for me (with my very limited coding skills).

Since Wagtail is a CMS, I think that it should have an easy way to include a language switcher in our templates and that it could be something like the {% wagtailuserbar %} template tag. This is beyond the scope of this app, so I think I will bring up the idea to the Wagtail developers and see what happens.

### Taken from Django Docs ###
```
<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}" />
        <select name="language" onclick="Bonjour">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                    {{ language.name_local }} ({{ language.code }})
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="Go" />
    </form>
```

**Comment by SalahAdDin** [comment]
Yes, but, this works with wagtailmodeltranslation?

**Comment by SalahAdDin** [comment]
No, this isn't works.
