### ISSUE TITLE
wagtail-localize discussion

### ISSUE THREAD

**Issue by jorenham** [infoportugal/wagtail-modeltranslation#331]
Wagtail 2.11 added native [i18n support](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html) with [wagtail-localize](https://github.com/wagtail/wagtail-localize). While it's architecture is very different (page-per-language instead of dynamic model fields), it appears that it provides the same features as `wagtail-modeltranslation`.

At this point, are there any considerable advantages of using `wagtail-modeltranslation` over `wagtail-localize` and will development continue, or is the plan to retire it? 

In any case, a migration tool (e.g. as management command) to convert to (and perhaps from) `wagtail-localize` might make a good addition.

**Comment by rainhead** [comment]
I suspect the silence is your response.
