### ISSUE TITLE
Copy content for EN-US not working 

### ISSUE THREAD

**Issue by ghost** [infoportugal/wagtail-modeltranslation#337]
When editing a page for the en-us language, the copy content function does not work.
First problem is the "en" button is not shown, so I cannot copy content from standard english.
Second problem is the other buttons don't work. If I click for example "copy content from fr" nothing seems to happen. Inspecting the situation I saw that clicking "copy content from fr" on the "en-us" fields, copies the content in the "en" field.

How can this be solved?

<img width="1051" alt="Schermata 2021-04-08 alle 09 57 57" src="https://user-images.githubusercontent.com/10153465/113990303-98e74b80-9851-11eb-89e8-21407ebf4f87.png">

**Comment by jorenham** [comment]
This was an annoying one to figure out, but I found a way to fix it in your own code:

In your app (that's below `"wagtail_modelstranslation"` in `settings.INSTALLED_APPS`), create a file named `wagtail_hooks.py` with the following contents:

```python
from wagtail.core import hooks


@hooks.register('insert_editor_js')
def streamfields_translation_copy():
    """
    Patches the wagtail_modeltranslation js responsible for the
    'Copy content from {{ lang }}' button on streamfields in
    'wagtail_modeltranslation/js/copy_stream_fields.js'
    """
    script = """
function extractInputId(currentStreamField) {
    const streamFieldInput = $(currentStreamField).find('.field-content input')[0];
    streamFieldInput.id = streamFieldInput.name;
    return streamFieldInput.name.split('-')[0];
}
    """

    return f'<script type="text/javascript">{script}</script>'
```

That's all :smiley: 

@infoportugal  would you mind including this as a fix?
