### ISSUE TITLE
Right way of importing wagtail-modeltranslation

### ISSUE THREAD

**Issue by rokondo** [infoportugal/wagtail-modeltranslation#339]
I found at [the documentation how to register models](https://wagtail-modeltranslation-docs.readthedocs.io/en/latest/Registering%20Models.html#changes-automatically-applied-to-the-model-class) another import 

```
from wagtail_modeltranslation.translation import TranslationOptions
from wagtail_modeltranslation.decorators import register
```
as on the start page:
```
from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register
```

so what is right way to do it?

**Comment by jorenham** [comment]
It's the same:
https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/translation.py#L3-L4

**Comment by rokondo** [comment]
Okay I guess for the future it is better to use the wagtail specific one, but thank you!
