### ISSUE TITLE
ImageChooserPanel is not translated

### ISSUE THREAD

**Issue by vnavascues** [infoportugal/wagtail-modeltranslation#34]
Hi,

Inside my translation.py one fields tuple includes an ImageChooserPanel field, but this is the unique field isn't translated. 
Are ImageChooserPanel supported or only FieldPanel?

Thanks

**Comment by rmartins90** [comment]
Hello vnacascues, ImageChooserPanel is not supported.
Could you please explain the use case?

**Comment by SalahAdDin** [comment]
I think that we want translate title and caption images :D.

**Comment by rmartins90** [comment]
Is set to be implemented soon.

**Comment by Alexandre27** [comment]
ImageChooserPanel is available since version 0.4
