### ISSUE TITLE
Wagtail  >= 2.14  'StreamValue' object has no attribute 'stream_data'

### ISSUE THREAD

**Issue by raminjrmz** [infoportugal/wagtail-modeltranslation#346]
I just upgraded my wagtail from 2.13.4 to 2.14.0 or 2.14.1  

Exception Type: | AttributeError
'StreamValue' object has no attribute 'stream_data'
/usr/local/lib/python3.7/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py, line 569, in meaningful_value

**Comment by jorenham** [comment]
I believe that this has been fixed, but the fix hasn't been released yet. For now, you could work around the issue by first uninstalling with e.g. `pip uninstall wagtail-modeltranslation`, and then reinstalling directly from the latest commit with e.g. `pip install git+https://github.com/infoportugal/wagtail-modeltranslation.git@c0c3788628b9d6c5bb3f6c3d06dbfd483c2b2a2a`

**Comment by andreasnuesslein** [comment]
Thanks to the team from infoportugal for this package! :)  Would you be able to create a new pypi-release for this?

I'm having the same issue.  :( 


Cheers

**Comment by jorenham** [comment]
@andreasnuesslein   I would if I could, but I don't have any push access.

**Comment by andreasnuesslein** [comment]
@DiogoMarques29 seems to be the person to talk to, about this.

**Comment by kleingeist** [comment]
is there any update on the next release?
i am currently blocked from updating to Wagtail 2.15 LTS because of the wagtail-modeltranslation.
using the latest `master` commit as suggested by @jorenham worked on our app. but we do not want to rely on unreleased code.


is there any help i can provide to progress with the next release?

**Comment by DiogoMarques29** [comment]
Hello.
We are planning a new release for next week.

**Comment by DiogoMarques29** [comment]
New version released. Can you guys give it a try?
Cheers

**Comment by andreasnuesslein** [comment]
have not tried yet but thanks :)

**Comment by andreasnuesslein** [comment]
@jorenham it works, thanks. but we might need another release soon  ( -> https://github.com/infoportugal/wagtail-modeltranslation/pull/353 )

cheers

**Comment by DiogoMarques29** [comment]
@andreasnuesslein @jorenham 
a new version has been release, check it out! ;)

**Comment by andreasnuesslein** [comment]
@DiogoMarques29  uhm ... which one? 0.10.18 has been out for a while.

cheers

**Comment by DiogoMarques29** [comment]
Yap, pre-release:
https://pypi.org/project/wagtail-modeltranslation/0.11rc3/

I'll give it like 2 weeks until a production release
