### ISSUE TITLE
"Copy content from: ..." buttons do not work within MultiFieldPanel

### ISSUE THREAD

**Issue by jorenham** [infoportugal/wagtail-modeltranslation#347]
`StreamFieldPanel`'s within a `MultiFieldPanel` has no header, so naturally it can't be found by [getStreamFieldHeader](https://github.com/infoportugal/wagtail-modeltranslation/blob/master/wagtail_modeltranslation/static/wagtail_modeltranslation/js/copy_stream_fields.js#L48).

**Comment by DiogoMarques29** [comment]
Fixed in the latest versions!
