### ISSUE TITLE
ImportError: cannot import name 'ugettext' from 'django.utils.translation' 

### ISSUE THREAD

**Issue by basitiyidir** [infoportugal/wagtail-modeltranslation#359]
It was removed in django 4.
How we can solve this problem.

https://stackoverflow.com/questions/71420362/django4-0-importerror-cannot-import-name-ugettext-lazy-from-django-utils-tra

I've been using Django 3 and django-mongoengine-filter for over a year.
I upgraded the app to Django 4.
The following error is coming.

I need to find a way to solve this. Because my whole project is affected.

<img width="1218" alt="a" src="https://user-images.githubusercontent.com/1632765/171807166-b0cefb4a-7627-4b0b-b88f-033cb21c2991.png">

**Comment by DiogoMarques29** [comment]
Hey @basitiyidir 
We just released a new version (0.11rc3) with those fixes. Give it a spin!

Cheers
