### ISSUE TITLE
Wagtail 4 Support

### ISSUE THREAD

**Issue by th3hamm0r** [infoportugal/wagtail-modeltranslation#367]
Wagtail 4.0 comes with a lot of changes to the UI and API, which won't work with the current state of wagtail-modeltranslation.
Do you have near plans to adapt the package for 4.0?
Maybe I could support you here.

**Comment by ArnarTumi** [comment]
+1 here

**Comment by LLoyderino** [comment]
> Hello!
> 
> No work has been done so far, but we will start maybe next week.
> 
> We are planning on having a new branch/version (0.13.x) that will have wagtail >= 4.0 support.
> 
> Has anyone started looking into the actual necessary work?

Hi, I gave an attempt at it. It seems to be working, you can find the PR here https://github.com/infoportugal/wagtail-modeltranslation/pull/368

**Comment by DiogoMarques29** [comment]
Hi @LLoyderino 
Thank you for your help!

I see that there is an error in linter checks and tests are not running for wagtail 4.

Anyway, I'm approving your PR and merge the code with my local changes (I've been working on this too, and have all tests passing with the new wagtail version). The best part is your "hack" with the titles CSS.

Expect for a new beta version today.

Cheers!
