### ISSUE TITLE
Locale picker appears twice for standard Django Model

### ISSUE THREAD

**Issue by andre-fuchs** [infoportugal/wagtail-modeltranslation#371]
Translating a standard Django model, I get two locale picker forms in the ModelAdmin "Edit" view of this model. See screenshot attached. Workin with release candidate 0.13 here. But had this issue before with other versions. The first locale picker form does not work. The second does. 

![Screenshot from 2022-11-27 12-44-43](https://user-images.githubusercontent.com/43378427/204133622-7b5d4cf7-4d1f-4336-a3dd-0449bc53880f.png)

**Comment by LLoyderino** [comment]
For some reason the `ModelAdmin`'s edit page has an empty `form` inside of `.content > header` which gets picked up by modeltranslate.

https://github.com/infoportugal/wagtail-modeltranslation/blob/fca44583cb95261a320f2f6472fb9fcf4ff1d050/wagtail_modeltranslation/static/wagtail_modeltranslation/js/language_toggles.js#L6

One thing that could be done is changing `.content form` to `.content > form`.

This would ensure that we're applying the language filter is only selecting the direct child of `.content` and not other forms within.

@DiogoMarques29 could this be of any help?

**Comment by DiogoMarques29** [comment]
Hey @LLoyderino 
Sure helps!

I'll check into this today, see if I can release rc2.

**Comment by DiogoMarques29** [comment]
Version 0.13rc2 released!

Feel free to give it a try!

Cheers

**Comment by andre-fuchs** [comment]
Works like a charm, this solved the issue.
