### ISSUE TITLE
Language Chooser missing on translatable snippet (v. 13rc2)

### ISSUE THREAD

**Issue by LLoyderino** [infoportugal/wagtail-modeltranslation#372]
Version:
- `wagtail = "~=4.1"`
- `wagtail-modeltranslation = "==0.13rc2"`

Relevant code parts:
```py
# translate.py
@register(RedactedModel)
class RedactedModelTR(TranslationOptions):
    fields = ("title",)
```

```py
# snippets.py
class RedactedModel(models.Model):
    icon = models.ForeignKey(
        "wagtailimages.Image",
        on_delete=models.SET_NULL,
        related_name="+",
        null=True,
        blank=True,
        verbose_name="REDACTED",
    )
    title = models.CharField(max_length=255, verbose_name="REDACTED")

    panels = [
        FieldPanel("icon"),
        FieldPanel("title"),
    ]

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "REDACTED"
        verbose_name_plural = "REDACTED"
```

Screenshot:
![issue image](https://i.imgur.com/zduV7G8.png)

**Comment by DiogoMarques29** [comment]
Hi @LLoyderino 

The last commit 8384969b must have introduced this bug. I'll check it today.

Cheers

**Comment by DiogoMarques29** [comment]
@LLoyderino 

Can you show how are you registering the snippet, since there is no decorator in your code? I'm not able to reproduce the bug.

**Comment by LLoyderino** [comment]
> @LLoyderino
> 
> Can you show how are you registering the snippet, since there is no decorator in your code? I'm not able to reproduce the bug.

I am using the decorator `@register_snippet` from the lib `from wagtail.snippets.models import register_snippet`

I forgot to add it  in my example code, my apologies

**Comment by DiogoMarques29** [comment]
Still not able to reproduce the bug.

Does your browser console shows any error? Or even if the `language_toggles.js` is being correctly injected?

**Comment by LLoyderino** [comment]
> Still not able to reproduce the bug.
> 
> Does your browser console shows any error? Or even if the `language_toggles.js` is being correctly injected?

Uh it fixed iself and I wasn't able to reproduce the bug myself.
