### ISSUE TITLE
Translated fields are flaky

### ISSUE THREAD

**Issue by mcosti** [infoportugal/wagtail-modeltranslation#376]
Hey everyone! I am working on a wagtail project using these versions:

```
wagtail==4.1.1
wagtail-modeltranslation==0.13rc3
```

My issue is that the fields in other languages are sometimes not being inserted into the DOM, so the button toggles are not doing anything.  
Changing a setting in django or restarting the service sometimes solves it, but the issue appears very soon after, so it's very flaky.

I tried it with this setting:

```python
WAGTAILMODELTRANSLATION_LOCALE_PICKER = False
```

But the issue remains the same. The fields in the promote tab (slug/title tag, etc) are appearing correctly.  

Let me know if I can provide more info. Thank you

**Comment by mcosti** [comment]
### When it doesn't work:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/16706410/216013427-4078253f-cc6b-481c-9eb6-231f286fc437.png">

### When it works:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/16706410/216013667-9d69c495-b71e-4c99-ac9c-298b7cca5ca2.png">

**Comment by mcosti** [comment]
I just tried now with wagtail version 4.0.4, the same problem occurs

**Comment by mcosti** [comment]
Okay, after two days of banging my head against the keyboard, I finally realised where the flakyness comes from.
It's a symptom of my fix for the translation loading flakyness that can be found here.

https://github.com/infoportugal/wagtail-modeltranslation/issues/374#issuecomment-1369148088

In my fix, I am loading both the PageTR and my own custom translations in ready, and sometimes it results to this:
![image](https://user-images.githubusercontent.com/16706410/216337369-793e0da6-7523-4b25-840c-21234f14eadd.png)

My own custom models are not registered (sometimes).  

The solution was to keep this part in the apps.py file:

'''python
class CmsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "cms"

    def ready(self):
        register_translators()


def register_translators():
    from wagtail.models import Page
    from wagtail_modeltranslation.translation import PageTR

    try:
        translator.register(Page, PageTR)  # hack while the package maintainer fixes the issue
    except AlreadyRegistered:
        pass
'''


And register the models normally in the translation.py file:

'''python
@register(ProductPage)
class ProductPageTR(TranslationOptions):
    fields = ("description",)
'''

**Comment by sukhada** [comment]
@mcosti I'm having the same issue, but when I try to use your solution, I'm getting the following error:

```
*** NameError: name 'translator' is not defined
```

Any idea why that might be happening?

**Comment by sukhada** [comment]
Actually I figured out my issue - I was still using `StreamFieldPanel` instead of `FieldPanel`, so that seems to have caused the glitchiness.
