### ISSUE TITLE
I can't delete webPage that contains a body translate

### ISSUE THREAD

**Issue by level-antoine** [infoportugal/wagtail-modeltranslation#381]
I have installed modeltransaltion for my coderedcms app. However when i create webPage with 2 body with 2 different langages, I can publish this but i can't delete this page. One error appear and display :

TypeError at /admin/pages/4/delete/

'NoneType' object is not iterable

Thanks for your help.

**Comment by DiogoMarques29** [comment]
Try executing steps 8 and 9 from the install guide:
```
Run python manage.py sync_page_translation_fields (repeat every time you add a new language)

If you're adding wagtail-modeltranslation to an existing site run python manage.py update_translation_fields
```
