### ISSUE TITLE
Wagtail 5.0 support

### ISSUE THREAD

**Issue by mcosti** [infoportugal/wagtail-modeltranslation#384]
Hey! Is there any plan for wagtail 5.0 support?

Thanks!

**Comment by jorenham** [comment]
For reference:
https://docs.wagtail.org/en/stable/releases/5.0.html#upgrade-considerations

**Comment by mcosti** [comment]
Thanks for your work, @jorenham !

@DiogoMarques29 I just tested his work and all works perfectly.
Could you please release a new version?

**Comment by jorenham** [comment]
For me it's working fine in production as well (django 4.2, wagtail 5.0, psycopg 3)

**Comment by DiogoMarques29** [comment]
Hey guys. Just released version 0.14.0.

Cheers
