### ISSUE TITLE
 -     inside language code cause error

### ISSUE THREAD

**Issue by timtan** [infoportugal/wagtail-modeltranslation#40]
![2015-11-16 6 53 35](https://cloud.githubusercontent.com/assets/179785/11180131/5ebf4fea-8c93-11e5-9abb-d554fe0094f7.png)

I find inside wagtail-modeltranslation/models.py . we should replace all "-"  to "_" in language code.  due to wagtail model translation produce model in the form "file_language_code"  while django make migration. 

it may cause problem while using language code such as zh-hant

while accessing language code to get the real field name. use build_localized_fieldname may be better

**Comment by SalahAdDin** [comment]
:+1:

**Comment by SalahAdDin** [comment]
What's about this?
