### ISSUE TITLE
SnippetViewSets are not working 

### ISSUE THREAD

**Issue by andreasnuesslein** [infoportugal/wagtail-modeltranslation#408]
Hello all :wave: ,

Wagtail 5.1 is proposing to move the Snippet-Admin-configuration into its own thing, within `wagtail_hooks.py`

https://docs.wagtail.org/en/stable/topics/snippets/registering.html#using-register-snippet-as-a-function  (scroll down a tad)

This new concept is not yet detected by `patch_wagtailadmin.py`.

Maybe for now a disclaimer would be enough: "Don't use the SnippetViewSet in wagtail_hooks.py as proposed by Wagtail. Wagtail-Modeltranslation does not pick this up yet." or something like that.

cheers

**Comment by DiogoMarques29** [comment]
Hey guys!
Fixed in v0.14.4 and v0.15.1
Give it a try!

**Comment by andreasnuesslein** [comment]
Thanks @DiogoMarques29 . .. I can't really find in which project I needed this :see_no_evil:  Thanks for implementing it anyways :)
