### ISSUE TITLE
TitleFieldPanel not keeping kwarg "apply_if_live"

### ISSUE THREAD

**Issue by belinux** [infoportugal/wagtail-modeltranslation#414]
When translating a TitleFieldPanel the fields are not on live sync by default, if you set the apply_if_live to True, this value it's missed during patching the field.

Example:
```
title_field = TitleFieldPanel('title', apply_if_live=True)
assert title_field.apply_if_live is True
```
later, once the field has been patched and translated
```
title_field_de = "TitleFieldPanel instance that has been language patched"
assert title_field_de.apply_if_live is False
```

**Comment by jomiq** [comment]
@belinux I have a patch for this, please help me test #417
