### ISSUE TITLE
TitleFieldPanel not patching correctly when TRANSLATE_SLUGS is False

### ISSUE THREAD

**Issue by jomiq** [infoportugal/wagtail-modeltranslation#416]
## Issue
The default title panel is not correct when TRANSLATE_SLUGS is disabled. 

## Expected behaviour
Panel provided by `FieldPanel`.

## Actual behaviour
Panel rendered by `TitleFieldPanel`.

**Comment by DiogoMarques29** [comment]
Fixed #417
