### ISSUE TITLE
Inherited fields are not pached when using django-modeltranslation > 0.19.0

### ISSUE THREAD

**Issue by tognee** [infoportugal/wagtail-modeltranslation#429]
Fields like `title` and `slug` are not being patched in wagtail admin page due to django-modeltranslation splitting the `fields` attribute into `local_fields` and `all_fields`.

I've been able to fix this by replacing all instances of `translator.get_options_for_model(...).fields` into `translator.get_options_for_model(...).all_fields`

**Comment by jorenham** [comment]
Care to submit a PR for this?

**Comment by tognee** [comment]
Hi, should the PR be retrocompatibile with old versions of the library or it just changes all instances of the attribute and add a new minimum version library requirement?

**Comment by jorenham** [comment]
Judging by previous releases, I believe it's fine to just set `django-modeltranslation>=0.19`. Maybe it's also wise to add an upper bound while you're at it, so that something like this wont happening again in the future. 

Perhaps @DiogoMarques29 can say more about this

**Comment by DiogoMarques29** [comment]
Hello!

We can add that requirement to version 0.15.2. Version 0.16 will be reserved for the new Wagtail LTS (currently version 5.2).
