### ISSUE TITLE
After saving 'Page' url_path of non default languages is broken

### ISSUE THREAD

**Issue by PredragPeranovic** [infoportugal/wagtail-modeltranslation#44]
I'm playing with this module trying to evaluate it for next project. I build small demo site, a blog to test building multi lingual website.

So the problem that I found is:
After editing and saving page that have nested url_path like: 
url_path_en = /home/predrags-blog/first-blog/ 
url_path_sr = /home/predragov-blog/prvi-blog/

it changes url_paths to:
url_path_en = /home/predragov-blog/first-blog/
url_path_sr = /home/predragov-blog/prvi-blog/

my default language is sr and it seams that url_path of non default languages is changed to contain parent path of default language + sulg of current document in appropriate language.

This get fixed after running /manage.py set_translation_url_paths, but it is not practical for me to run it every time when I change something on website.

I make a quick fix, I hope it will be some use for you before you finding more elegant solution.

in wagtail_modeltranslation/models.py
```python
       def set_url_path(self, parent):
        """
        This method override populates url_path for each specified language.
        This way we can get different urls for each language, defined
        by page slug.
        """
       # quick fix start ( line 422)
        if parent:
            parent = parent.content_type.model_class().objects.get(pk=parent.pk)
       # quick fix end

        for lang in settings.LANGUAGES:
            if parent:
```

All best

**Comment by rmartins90** [comment]
Fixed in v0.3.6
