### ISSUE TITLE
Are the advanced settings in the Documentation implemented

### ISSUE THREAD

**Issue by agelinas** [infoportugal/wagtail-modeltranslation#49]
I'm the one who has created the documentation based on django-modeltranslation. I have included the advanced settings.

Today I have tried some of the advanced settings, such as 
- MODELTRANSLATION_DEFAULT_LANGUAGE = 'fr',
- MODELTRANSLATION_AUTO_POPULATE = True, 
- etc.

I am wondering if the advanced settings are implemented in wagtail-modeltranslation? If not, I will remove that section so no one is going to be misled by the documentation.

Thank you,
Alain

**Comment by dpratter** [comment]
I tried to use 'MODELTRANSLATION_DEFAULT_LANGUAGE' and 'MODELTRANSLATION_LANGUAGES' but unfortunately (at least) those two settings do not seem to be implemented.

**Comment by SalahAdDin** [comment]
The documentation is now incompleted, can you update it?

**Comment by Alexandre27** [comment]
The advanced settings are provided for django-modeltranslation and since version 0.6 it is a dependency, they should work as documented in django-modeltransaltion.
