### ISSUE TITLE
MODELTRANSLATION_DEFAULT_LANGUAGE not in LANGUAGES setting.

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#53]
I see all info in the documentation but i haven't idea what's the problem.
![ccct - -run-media-salahaddin-data-proyectos-trabajo-ccct - -ccct-ccct-settings-base py - pycharm 5 0 3_025](https://cloud.githubusercontent.com/assets/5034215/12370423/64337760-bbde-11e5-9de5-df983ff0733b.png)

'es' are in settings.LANGUAGE, so, what's the problem?

I don't understand: i want put es as default language and en tr as translatable languages, what settings i need?

Ok, i believe that i solve this:
![ccct - -run-media-salahaddin-data-proyectos-trabajo-ccct - -ccct-ccct-settings-base py - pycharm 5 0 3_026](https://cloud.githubusercontent.com/assets/5034215/12370598/e1ad0386-bbe4-11e5-9633-579d9326c010.png)

But if you cant see i have other error:
I built a new migration and make it, delete all es fields. But, when i try edit a page, i have these error:
![fielderror at -admin-pages-28-edit- - mozilla firefox_027](https://cloud.githubusercontent.com/assets/5034215/12370604/1666468c-bbe5-11e5-8ae8-3b40f31a0998.png)

Why? I suppose that es fields is the primary fields. So, why i have this error?

Ok, I delete the second option and put the first, migrate and getback es fields and all is well, but:
![phppgadmin - mozilla firefox_028](https://cloud.githubusercontent.com/assets/5034215/12370710/51cef4cc-bbe9-11e5-8c4d-45c9b4b6eedc.png)
![wagtail - editando nuevo - mozilla firefox_029](https://cloud.githubusercontent.com/assets/5034215/12370708/40df2dc6-bbe9-11e5-920f-0ed17e8269ec.png)
If i have info in original fields why es field haven't these info?

I mean, i understand that if i put a default language, when i writter information for these language, original field have this information, right?

**Comment by DiogoMarques29** [comment]
hi @SalahAdDin 
I belive the problem is that in MODELTRANSLATION_LANGUAGES you don't have es, so he does not creates fields for es language. When you say MODELTRANSLATION_DEFAULT_LANGUAGE is 'es', that does not means he will create fields for es, you have to use in MODELTRANSLATION_LANGUAGES or in settings.Languages

**Comment by SalahAdDin** [comment]
No, now i have translation es fields, isn't it the last problem.

The last problemas is that i have translation es fields but without information, didn't take any information since original fields.

**Comment by SalahAdDin** [comment]
I can make fixes manually through phppgadmin, but, in the web site I can't do this, I have many pages.

**Comment by SalahAdDin** [comment]
:+1: This is very urgent!!!!

**Comment by SalahAdDin** [comment]
@DiogoMarques29 @rmartins90 @agelinas 

This is the end, finally, i can use model tranlation!

You forget it explain us that by default this app doen't syncronize the fields: http://django-modeltranslation.readthedocs.org/en/latest/commands.html

I was doing other test and put manage.py for see all commands and i see that wagtail modeltranslation have a few commands, i can't find it in the documentation, so, i though, this apps is a django-modeltranslation fork and i found the commands in his docs.

Put completly documentation! Going to better.
