### ISSUE TITLE
Changing title shouldn't change slug on live pages

### ISSUE THREAD

**Issue by benebun** [infoportugal/wagtail-modeltranslation#54]
Changing the title of a live page also changes its slug, without warning and with usability/SEO implications.

This was also the case in wagtail itself, fixed with torchbox/wagtail#1810 for torchbox/wagtail#528 preventing a slug change when the page is live.

The fix for wagtail-modeltranslation should be in [wagtail_translated_slugs.js:9](https://github.com/infoportugal/wagtail-modeltranslation/blob/e59aa99f4b58a1a6a0c73b37efc0d7597ebc0705/wagtail_modeltranslation/static/modeltranslation/js/wagtail_translated_slugs.js#L9)

``` javascript
if ($('body').hasClass('create') || (!$('#id_slug_'+lang_code).data('previous-val').length || cleanForSlug($('#id_title_'+lang_code).data('previous-val')) === $('#id_slug_'+lang_code).data('previous-val'))) {
// only update slug if the page is being created from scratch, if slug is completely blank, or if title and slug prior to typing were identical
```

Not sure why the last check "if title and slug prior to typing were identical" is required/sensible?

**Comment by akhayyat** [comment]
It'd be nice to have this fixed here in wagtail-modeltranslation so as not to change wagtail behavior.
