### ISSUE TITLE
Add translation of streamfield to a Multifield-Panel breaks Javascript

### ISSUE THREAD

**Issue by MagdaN** [infoportugal/wagtail-modeltranslation#55]
I wanted to add a collapcollapsible Multifield-Panel for each language which works fine except for the fact that the streamfield does not open when clicking on the plus button or any of the available block-icons buttons. I get an error in the javascript which says: Uncaught TypeError: Cannot read property 'innerHTML' of undefined (copy_stream_fields.js: 20).

It seems that the script is looking for a h2 that is not there.

**Comment by DhiaTN** [comment]
+1

**Comment by DhiaTN** [comment]
+1

**Comment by benjaoming** [comment]
It seems that also StreamFields are broken in general, I get `TypeError: blockOpts is undefined` using Wagtail 1.3.1

**Comment by benjaoming** [comment]
Problem seems to be related to `StreamBlock.render_list_member` never being called when the model inherits from TranslationMixin.

**Comment by benjaoming** [comment]
(deleted my comments because it turns out my javascript errors were self-inflicted, I used a FieldPanel instead of a StreamFieldPanel for my StreamField)

**Comment by DiogoMarques29** [comment]
Please open a new Issue if the bug persists in latest version.
