### ISSUE TITLE
Problem on python shell

### ISSUE THREAD

**Issue by EduardoNogueira** [infoportugal/wagtail-modeltranslation#57]
On the python shell when we try "Model".objects.all or "Model".objects.first to get the pages that returns an "bound method NewMultilingualManager."all or first" of wagtail_modeltranslation.translator.NewMultilingualManager object".

**Comment by DhiaTN** [comment]
+1

**Comment by fdemmer** [comment]
`all()` and `first()` are *methods* of the manager, you need to call them --> `()`

**Comment by SalahAdDin** [comment]
:+1:

**Comment by Alexandre27** [comment]
Like @fdemmer said, those are methods so you have to use `.all()` and `.first()` to call them.
