### ISSUE TITLE
[Feature] Snippets translation

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#58]
Hi guys, how are you? 

I want talk about something a few important: translate snippets.

Isn't very important at first view but it's simple thing, snippets, at least wagtail demo snippets have some unique field for translation: text. I think that will be ugly have all weg site translate except a snippet, don't it?

Ok, i try to translate a snippet and i have the next problem with it:
![attributeerror at -admin-snippets-core-advert- - mozilla firefox_059](https://cloud.githubusercontent.com/assets/5034215/12823812/1d150c78-cb3c-11e5-8264-b1a054840e58.png)
![seleccion_060](https://cloud.githubusercontent.com/assets/5034215/12823819/27c231e6-cb3c-11e5-96bd-6603bf8a2c75.png)
![seleccion_061](https://cloud.githubusercontent.com/assets/5034215/12823818/27c05d58-cb3c-11e5-8b6a-bbe38f907adc.png)

Can do you anithing for solve it? Thanks.

PD: I can verify what happen if i try add new snippet:
![attributeerror at -admin-snippets-core-advert-add- - mozilla firefox_062](https://cloud.githubusercontent.com/assets/5034215/12823927/a7f76106-cb3c-11e5-8890-2b5f86b00223.png)

**Comment by Alexandre27** [comment]
Starting in version 0.5 we don't have any problems translating Snippets and BaseSetting models.
