### ISSUE TITLE
Problem updating field with null value

### ISSUE THREAD

**Issue by rmartins90** [infoportugal/wagtail-modeltranslation#6]
Default language field doesn't update for null value

**Comment by rmartins90** [comment]
https://github.com/infoportugal/wagtail-modeltranslation/commit/df2579c33c493197bd3b53340b127949053e4d56

**Comment by SalahAdDin** [comment]
Hi men, i have a ask for you:

How you put the Embed Video and Galleries options in the wagtail admin menu?

Thank you.
