### ISSUE TITLE
Update descendant URL paths not implemented: moving pages & changing slugs broken

### ISSUE THREAD

**Issue by fdemmer** [infoportugal/wagtail-modeltranslation#63]
When **moving** a page or **changing the slug** of a page **with descendants**, all the descendant's `url_paths` must be updated to reflect the new slug (new slugs in every language to be precise) of the parent.

Currently the patched `Page.move()` method does this for the moved page. The call to `set_url_path()` (`wagtail_modeltranslation/models.py:450`) makes sure the `url_path` of the moved page is updated. However, if that page has descendants, those `url_paths` will be broken.

This is because `Page._update_descendant_url_paths()` (`wagtail/wagtailcore/models.py:506`) is not patched and in the original implementation is using raw sql and operates only on the `Page` table (and therefore the untranslated `url_path`), not the specific model which carries the translated slugs.

The same `Page._update_descendant_url_paths()` is called by `Page.save()` (currently _not_ patched by modeltranslate) to propagare `slug`/`url_path` changes of parents to to their descendants. This means, that changing the slug of any parent page, breaks the children's `url_paths`.

**Comment by benebun** [comment]
In combination with #54 this is pretty bad: renaming a title of a parent page changes its slug and breaks the urls of descendant pages.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by pyMan** [comment]
As said before, Page._update_descendant_url_paths needs patch because of the untranslated url_path.

Anyway I think that the patched Page.move should call update_descendant_url_paths on self and not on new_self: in this way all the descendants Page.url_path will be correctly updated.

Is wagtail modeltranslation abandoned?

**Comment by Alexandre27** [comment]
Fixed in version 0.6
