### ISSUE TITLE
Active wagtail admin language is used to save translated fields on Page (eg. title, slug)

### ISSUE THREAD

**Issue by fdemmer** [infoportugal/wagtail-modeltranslation#64]
Wagtail admin uses `LocaleMiddleware` to detect browser language.

Imagine a custom page model translating the `title` field. When using the wagtail admin in eg German, the value set on the `title_de` field will also be written to the `title` field of `Page` (the wagtail built in root model) when saving. When using the admin in eg. English, the `Page.title` will contain the English value after saving.

When editors with different language operating systems/browsers use the admin (which is not uncommon when operating a multi-language site), the languages of the `title` fields of the various pages stored will vary.

This has a number of problematic side effects:
- The `Page.title` field is used in the list views of wagtail admin. So the list will show a mix of all kinds of languages and make it difficult for editors to find the articles they are looking for.
- Speaking of "finding things": when using the basic wagtail setup with DB search backend, the translated fields cannot be searched. This is a wagtail limitation, only fields on the `Page` model can be searched with this backend. 
  However, that would not be a problem, if the titles on the `Page` model would stay consistent eg. "always in English". Imagine using the word "district" in the title for eg a page describing a location: you'd have to search for "bezirk" if the last saving editor happened used a German browser, "quartier" if they were using French etc. You just never know what to search for.

The "translation overloaded" fields of `Page` should always contain the same language, probably best to use `settings.LANGUAGE_CODE`.

**Comment by Alexandre27** [comment]
See comment on PR #65
