### ISSUE TITLE
Remove TranslationMixin and SnippetsTranslationMixin

### ISSUE THREAD

**Issue by Alexandre27** [infoportugal/wagtail-modeltranslation#69]
Remove the obligation to subclass this classes on pages and snippets. It is desired that the patches are made during the registration.

**Comment by Alexandre27** [comment]
To close this issue it is needed to make unit tests for the overridden page methods (move, set_url_path, route get_site_root_paths, relative_url and url) and for the patching of the forms to see if the translated fields keep the required status of the original field.

**Comment by benjaoming** [comment]
Can this be closed now that the above commit has been pushed to master?
