### ISSUE TITLE
Copy page does not creates slugs for all languages

### ISSUE THREAD

**Issue by DiogoMarques29** [infoportugal/wagtail-modeltranslation#7]
Hi there, 

When copying a page, the slug field doesn't get created for all languages. Imagine we have a page with both title_pt and title_en and we want to copy a page "teste" giving it the name "teste 2" and slug "teste-2", it will create the new page with the fields title_pt "teste",  title_en "teste 2", slug_pt "teste" and slug_en "teste-2". So in conclusion it will only creates the fields for the current browser language (mine is en).

best regards,
Diogo Marques

**Comment by pyMan** [comment]
This needs:

- A patch to wagtailadmin.views.pages.copy to pass all title* and slug* fields to page.copy in the update_attrs dict
- A patch to wagtailadmin.forms.CopyForm to create a new title field and a new slug field for each language. The form has to work on the specific page to see all the language fields
- A patch to the template wagtailadmin.pages.copy.html to render all the new fields

I did all this changes to wagtail directly just to test and it works. Now how to bring all this in wagtail-modeltranslation? How to patch a view?

**Comment by SalahAdDin** [comment]
Many problems!
