### ISSUE TITLE
0.5.x Python3 compatibility

### ISSUE THREAD

**Issue by nikonikoniko** [infoportugal/wagtail-modeltranslation#73]
`wagtail-modeltranslation-0.4.2` is python3 compatible, 

`wagtail-modeltranslation-0.5.0a0` is not in `wagtail-modeltranslation/patch_wagtailadmin.py`

```
  File "/home/uer/code/hzk/lib/python3.5/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 92, in __init__
    for related_name, formset in form.formsets.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by Alexandre27** [comment]
PR merged on branch release/v0.5. Version 0.6 also has support for python 3 and is available in pip.
