### ISSUE TITLE
Changing title doesn't reflect on list view

### ISSUE THREAD

**Issue by benebun** [infoportugal/wagtail-modeltranslation#78]
Hi,

haven't found an issue for that yet:
Changing the title of a page doesn't reflect on the list view in the admin, this still displays the old original title, which is of course confusing for editors.

wagtail 1.3.1
wagtail-modeltranslation 0.4.4

**Comment by benebun** [comment]
This seems to only affect articles in draft mode.

**Comment by dpratter** [comment]
Since wagtail 1.5.x it is possible to "solve" this issue with a wagtail-hook.

Create a wagtail_hooks.py file in one of your app directories and add the following code:

```
from __future__ import unicode_literals

from wagtail.wagtailcore import hooks

@hooks.register('construct_explorer_page_queryset')
def show_translated_pages(parent_page, pages, request):
    """
    Display page titles in explorer list view in session language by using 
    specific Page models instead of wagtailcore.Page models.
    """
    return pages.specific()
```

With this hook page titles in explorer list views will be displayed in an editor's current session language.

**Comment by DiogoMarques29** [comment]
Please re-open if the problem persists with new wagtail_modeltranslation version.
