### ISSUE TITLE
Problems with CustomPageManager

### ISSUE THREAD

**Issue by pyMan** [infoportugal/wagtail-modeltranslation#95]
Hello,
I need to add some extra QuerySet methods to wagtail.PageQuerySet and I did it following the example [here](http://docs.wagtail.io/en/v1.7/topics/pages.html?highlight=PageQuerySet#custom-page-managers).
```
from django.db import models
from django.utils import timezone
from wagtail.wagtailcore.models import Page, PageManager, PageQuerySet

class EventPageQuerySet(PageQuerySet):
    def future(self):
        today = timezone.localtime(timezone.now()).date()
        return self.filter(start_date__gte=today)

class EventPage(Page):
    start_date = models.DateField()

    objects = PageManager.from_queryset(EventPageQuerySet)()
```

I have an error when using the new queryset method. I think something is not well monkey-patched in translator.py but I don't understand what.

```
>>> EventPage.objects.future()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\xxxxxxxxxxxxxxxx\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
AttributeError: 'MultilingualPageQuerySet' object has no attribute 'future'
```

Using django 1.8.x

Please help

**Comment by SalahAdDin** [comment]
Help pĺease!

**Comment by pyMan** [comment]
It may just be a wagtail problem. See wagtail/wagtail#3250. I'll give a try in the next days.

**Comment by Alexandre27** [comment]
@pyMan Was it a wagtail problem? 
Because in the [django-modeltranslation docs](http://django-modeltranslation.readthedocs.io/en/latest/usage.html#multilingual-manager) the custom queryset manager functions are retained.

**Comment by pyMan** [comment]
Hi @Alexandre27 .

It's related to wagtail. Still having the issue but seems I found a way to the solution.
