### ISSUE TITLE
Slug already in use

### ISSUE THREAD

**Issue by pyMan** [infoportugal/wagtail-modeltranslation#98]
If you have already an existing Page with slug_en "test" and slug_it "test" and you try creating a sibling Page with the same slug it fails with error 500 instead of giving a friendly message.

```
Exception Type: ValidationError at /cms/admin/pages/add/my_cms/freepage/3/
Exception Value: {u'slug': [u'This slug is already in use']}
```

There is not check when cleaning the form about the translated fields.

Tested with wagtail 1.7 and wagtailmodeltranslation 0.5.0a1

**Comment by Alexandre27** [comment]
Fixed in version 0.6
